# Generated by Django 5.2.15 on 2026-06-25 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exploitations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiviteTaxonomie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campagne', models.PositiveIntegerField(verbose_name='campagne')),
                ('libelle', models.CharField(max_length=255, verbose_name='activité')),
                ('code_nace', models.CharField(blank=True, max_length=20, verbose_name='code NACE')),
                ('objectif', models.CharField(choices=[('attenuation', 'Atténuation du changement climatique'), ('adaptation', 'Adaptation au changement climatique'), ('eau', 'Eau et ressources marines'), ('circulaire', 'Économie circulaire'), ('pollution', 'Prévention de la pollution'), ('biodiversite', 'Biodiversité et écosystèmes')], default='attenuation', max_length=15, verbose_name='objectif de contribution')),
                ('eligible', models.BooleanField(default=False, verbose_name='éligible')),
                ('contribution', models.BooleanField(default=False, verbose_name='contribution substantielle')),
                ('dnsh', models.JSONField(blank=True, default=dict, verbose_name='DNSH par objectif')),
                ('garanties', models.BooleanField(default=False, verbose_name='garanties minimales')),
                ('chiffre_affaires', models.FloatField(blank=True, null=True, verbose_name="chiffre d'affaires (€)")),
                ('capex', models.FloatField(blank=True, null=True, verbose_name='CapEx (€)')),
                ('opex', models.FloatField(blank=True, null=True, verbose_name='OpEx (€)')),
                ('justification', models.TextField(blank=True, verbose_name='justification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites_taxonomie', to='exploitations.exploitation')),
            ],
            options={
                'verbose_name': 'activité Taxonomie',
                'verbose_name_plural': 'activités Taxonomie',
                'ordering': ('-campagne', 'libelle'),
                'indexes': [models.Index(fields=['exploitation', 'campagne'], name='environneme_exploit_a67a39_idx')],
            },
        ),
    ]
