# Generated by Django 5.2.15 on 2026-07-17 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environnement', '0001_initial'),
        ('exploitations', '0006_rename_telephone_fields'),
        ('parcelles', '0002_parcelle_acquired_at_parcelle_cadastre_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biodiversite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='score biodiversité (0-100)')),
                ('especes_vegetales', models.IntegerField(blank=True, null=True, verbose_name='espèces végétales')),
                ('especes_animales', models.IntegerField(blank=True, null=True, verbose_name='espèces animales')),
                ('haies_ml', models.FloatField(blank=True, null=True, verbose_name='haies (ml)')),
                ('jachere_ha', models.FloatField(blank=True, null=True, verbose_name='jachère (ha)')),
                ('observations', models.TextField(blank=True, verbose_name='observations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_biodiversite', to='exploitations.exploitation')),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_biodiversite', to='parcelles.parcelle')),
            ],
            options={
                'verbose_name': 'fiche biodiversité',
                'verbose_name_plural': 'fiches biodiversité',
                'ordering': ('-date',),
            },
        ),
    ]
