# Generated by Django 5.2.15 on 2026-06-24 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exploitations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AidePAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campagne', models.PositiveIntegerField(verbose_name='campagne')),
                ('categorie', models.CharField(choices=[('DPB', 'DPB — Droits à paiement de base'), ('ECO', 'Éco-régime'), ('REDIST', 'Paiement redistributif'), ('JA', 'Aide jeune agriculteur'), ('COUPLEE', 'Aides couplées'), ('ICHN', 'ICHN — Indemnité handicap naturel'), ('MAEC', 'MAEC — Mesures agro-environnementales'), ('BIO', 'Agriculture biologique'), ('ASSUR', 'Assurance récolte'), ('AUTRE', 'Autre')], default='DPB', max_length=10, verbose_name='catégorie')),
                ('libelle', models.CharField(blank=True, max_length=255, verbose_name='libellé')),
                ('montant', models.FloatField(blank=True, null=True, verbose_name='montant (€)')),
                ('surface_ha', models.FloatField(blank=True, null=True, verbose_name='surface (ha)')),
                ('statut', models.CharField(choices=[('prevu', 'Prévu'), ('accorde', 'Accordé'), ('paye', 'Payé')], default='prevu', max_length=10, verbose_name='statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aides_pac', to='exploitations.exploitation')),
            ],
            options={
                'verbose_name': 'aide PAC',
                'verbose_name_plural': 'aides PAC',
                'ordering': ('-campagne', 'categorie'),
                'indexes': [models.Index(fields=['exploitation', 'campagne'], name='pac_aidepac_exploit_b0fd76_idx')],
            },
        ),
    ]
