# Generated by Django 5.2.15 on 2026-08-01 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ressourceeau',
            name='station_pompage',
            field=models.ForeignKey(blank=True, help_text="Station installée sur ce point d'eau. Forme un cycle avec Equipement.borne_source, résolu en second passage à l'import.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_eau', to='dti.equipement', verbose_name='station de pompage'),
        ),
    ]
