# Generated by Django 5.2.15 on 2026-08-25 20:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exploitations', '0021_exploitation_logo'),
        ('parcelles', '0009_parcelle_orientation_rangs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=255, verbose_name='nom')),
                ('type_depot', models.CharField(choices=[('hangar', 'Hangar'), ('silo', 'Silo'), ('cuve', 'Cuve'), ('chambre_froide', 'Chambre froide'), ('local_phyto', 'Local phytosanitaire'), ('magasin', 'Magasin'), ('exterieur', 'Extérieur'), ('autre', 'Autre')], default='hangar', max_length=20, verbose_name='type')),
                ('localisation', models.CharField(blank=True, max_length=255, verbose_name='localisation')),
                ('capacite', models.FloatField(blank=True, null=True, verbose_name='capacité')),
                ('unite_capacite', models.CharField(blank=True, choices=[('kg', 'kg'), ('t', 't'), ('l', 'L'), ('hl', 'hL'), ('m3', 'm³'), ('unite', 'unité'), ('sac', 'sac'), ('big_bag', 'big bag'), ('palette', 'palette'), ('dose', 'dose')], max_length=10, verbose_name='unité de capacité')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depots', to='exploitations.exploitation')),
            ],
            options={
                'verbose_name': 'dépôt',
                'verbose_name_plural': 'dépôts',
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=255, verbose_name='désignation')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='référence')),
                ('categorie', models.CharField(choices=[('semence', 'Semences et plants'), ('engrais', 'Engrais'), ('amendement', 'Amendements'), ('phyto', 'Produits phytosanitaires'), ('biocontrole', 'Biocontrôle'), ('aliment', 'Aliments du bétail'), ('litiere', 'Litière et fourrage'), ('veterinaire', 'Produits vétérinaires'), ('carburant', 'Carburants et lubrifiants'), ('piece', 'Pièces détachées'), ('emballage', 'Emballages'), ('recolte', 'Récolte'), ('autre', 'Autre')], default='autre', max_length=15, verbose_name='catégorie')),
                ('unite', models.CharField(choices=[('kg', 'kg'), ('t', 't'), ('l', 'L'), ('hl', 'hL'), ('m3', 'm³'), ('unite', 'unité'), ('sac', 'sac'), ('big_bag', 'big bag'), ('palette', 'palette'), ('dose', 'dose')], default='kg', max_length=10, verbose_name='unité')),
                ('quantite', models.FloatField(default=0, verbose_name='quantité en stock')),
                ('seuil_alerte', models.FloatField(blank=True, null=True, verbose_name="seuil d'alerte")),
                ('prix_unitaire', models.FloatField(blank=True, null=True, verbose_name='prix unitaire (€)')),
                ('fournisseur', models.CharField(blank=True, max_length=255, verbose_name='fournisseur')),
                ('lot', models.CharField(blank=True, max_length=100, verbose_name='n° de lot')),
                ('date_peremption', models.DateField(blank=True, null=True, verbose_name='date de péremption')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles_stock', to='exploitations.exploitation')),
                ('depot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='stock.depot', verbose_name='dépôt')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='Mouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_mouvement', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie'), ('correction', "Correction d'inventaire")], default='sortie', max_length=12, verbose_name='sens')),
                ('motif', models.CharField(choices=[('achat', 'Achat'), ('recolte', 'Récolte rentrée'), ('retour', 'Retour de chantier'), ('epandage', 'Épandage / traitement'), ('semis', 'Semis / plantation'), ('alimentation', 'Alimentation du bétail'), ('vente', 'Vente'), ('perte', 'Perte, casse ou péremption'), ('inventaire', 'Inventaire'), ('autre', 'Autre')], default='autre', max_length=15, verbose_name='motif')),
                ('quantite', models.FloatField(verbose_name='quantité')),
                ('quantite_apres', models.FloatField(default=0, verbose_name='stock après mouvement')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
                ('cout_unitaire', models.FloatField(blank=True, null=True, verbose_name='coût unitaire (€)')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='stock.article')),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_stock', to='exploitations.exploitation')),
                ('parcelle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parcelles.parcelle', verbose_name='parcelle')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'mouvement de stock',
                'verbose_name_plural': 'mouvements de stock',
                'ordering': ('-date', '-created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='depot',
            index=models.Index(fields=['exploitation', 'type_depot'], name='stock_depot_exploit_85ad56_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['exploitation', 'categorie'], name='stock_artic_exploit_4cb802_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvement',
            index=models.Index(fields=['exploitation', '-date'], name='stock_mouve_exploit_3185e7_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvement',
            index=models.Index(fields=['article', '-date'], name='stock_mouve_article_397911_idx'),
        ),
    ]
