# Generated by Django 5.2.15 on 2026-08-25 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0009_devis_signature_date_devis_signature_mention_and_more'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvement',
            name='recolte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrees_stock', to='finances.recolte', verbose_name="récolte d'origine"),
        ),
    ]
