# Generated by Django 5.2.15 on 2026-06-23 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exploitations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmtpConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField(default=587)),
                ('secure', models.BooleanField(default=False)),
                ('user', models.CharField(max_length=320)),
                ('password', models.TextField()),
                ('from_name', models.CharField(default='Isidor', max_length=255)),
                ('from_email', models.EmailField(max_length=254)),
                ('enabled', models.BooleanField(default=True)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_status', models.CharField(blank=True, choices=[('ok', 'OK'), ('error', 'Erreur')], max_length=8)),
                ('last_test_error', models.TextField(blank=True)),
                ('exploitation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='smtp_config', to='exploitations.exploitation')),
            ],
            options={
                'verbose_name': 'configuration SMTP',
                'verbose_name_plural': 'configurations SMTP',
            },
        ),
    ]
