# Generated by Django 5.2.15 on 2026-06-24 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipe', '0001_initial'),
        ('exploitations', '0001_initial'),
        ('operations', '0002_delete_intervention'),
        ('parcelles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intervention_type', models.CharField(choices=[('irrigation', 'Irrigation'), ('traitement', 'Traitement'), ('fertilisation', 'Fertilisation'), ('recolte', 'Récolte'), ('semis', 'Semis'), ('travail_sol', 'Travail du sol'), ('taille', 'Taille'), ('palissage', 'Palissage'), ('desherbage', 'Désherbage'), ('eclaircissage', 'Éclaircissage'), ('effeuillage', 'Effeuillage'), ('vendange', 'Vendange'), ('maintenance', 'Maintenance'), ('observation', 'Observation'), ('autre', 'Autre')], max_length=15)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='planifiee', max_length=12)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_hours', models.FloatField(blank=True, null=True)),
                ('product', models.CharField(blank=True, max_length=255)),
                ('dose', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('surface', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('voice_transcript', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('voice', 'Vocal'), ('manual', 'Manuel'), ('ai', 'IA')], default='manual', max_length=10)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipe.teammember')),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='exploitations.exploitation')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.machine')),
                ('parcelle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parcelles.parcelle')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipe.task')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'intervention',
                'verbose_name_plural': 'interventions',
                'ordering': ('-start_time',),
                'indexes': [models.Index(fields=['exploitation', '-start_time'], name='interventio_exploit_af10ae_idx')],
            },
        ),
    ]
