# Generated by Django 5.2.15 on 2026-07-25 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exploitations', '0010_exploitation_meteo_masquer_lieu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='nom / raison sociale')),
                ('type_client', models.CharField(choices=[('particulier', 'Particulier'), ('professionnel', 'Professionnel'), ('cooperative', 'Coopérative'), ('grossiste', 'Grossiste'), ('distributeur', 'Distributeur / GMS'), ('restauration', 'Restauration'), ('collectivite', 'Collectivité'), ('export', 'Export'), ('autre', 'Autre')], default='professionnel', max_length=15, verbose_name='type')),
                ('statut', models.CharField(choices=[('prospect', 'Prospect'), ('actif', 'Actif'), ('inactif', 'Inactif'), ('archive', 'Archivé')], default='prospect', max_length=10, verbose_name='statut')),
                ('contact_principal', models.CharField(blank=True, max_length=255, verbose_name='contact principal')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='téléphone')),
                ('site_web', models.CharField(blank=True, max_length=255, verbose_name='site web')),
                ('adresse', models.CharField(blank=True, max_length=255, verbose_name='adresse')),
                ('code_postal', models.CharField(blank=True, max_length=10, verbose_name='code postal')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='ville')),
                ('pays', models.CharField(blank=True, max_length=100, verbose_name='pays')),
                ('siret', models.CharField(blank=True, max_length=20, verbose_name='SIRET')),
                ('tva_intracom', models.CharField(blank=True, max_length=20, verbose_name='TVA intracommunautaire')),
                ('delai_paiement_jours', models.PositiveIntegerField(blank=True, null=True, verbose_name='délai de paiement (jours)')),
                ('ca_annuel', models.FloatField(blank=True, null=True, verbose_name="chiffre d'affaires annuel (€)")),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='exploitations.exploitation')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='nom')),
                ('fonction', models.CharField(blank=True, max_length=255, verbose_name='fonction')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='téléphone')),
                ('principal', models.BooleanField(default=False, verbose_name='contact principal')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='client.client')),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
                'ordering': ('-principal', 'nom'),
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['exploitation', 'statut'], name='client_clie_exploit_a27403_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['client', 'principal'], name='client_cont_client__58e4e1_idx'),
        ),
    ]
