# Generated by Django 5.2.15 on 2026-07-25 14:14

from django.db import migrations, models


def repartir_categories(apps, schema_editor):
    """« particulier »/« professionnel » étaient des types : ils deviennent la catégorie."""
    Client = apps.get_model("client", "Client")
    Client.objects.filter(type_client="particulier").update(categorie="particulier", type_client="")
    Client.objects.filter(type_client="professionnel").update(categorie="professionnel", type_client="autre")


def rassembler_categories(apps, schema_editor):
    Client = apps.get_model("client", "Client")
    Client.objects.filter(categorie="particulier").update(type_client="particulier")


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_delete_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='categorie',
            field=models.CharField(choices=[('particulier', 'Particulier'), ('professionnel', 'Professionnel')], default='professionnel', max_length=15, verbose_name='catégorie'),
        ),
        migrations.AlterField(
            model_name='client',
            name='type_client',
            field=models.CharField(blank=True, choices=[('cooperative', 'Coopérative'), ('grossiste', 'Grossiste'), ('distributeur', 'Distributeur / GMS'), ('restauration', 'Restauration'), ('collectivite', 'Collectivité'), ('export', 'Export'), ('autre', 'Autre')], default='autre', max_length=15, verbose_name='type'),
        ),
        migrations.RunPython(repartir_categories, rassembler_categories),
    ]
