# Generated by Django 5.2.15 on 2026-07-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_client_categorie_alter_client_type_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='prenom',
            field=models.CharField(blank=True, max_length=255, verbose_name='prénom'),
        ),
    ]
