# Generated by Django 5.2.15 on 2026-07-25 14:46

from django.db import migrations, models

from core.adresse import split_voie


def decouper_adresses(apps, schema_editor):
    """« 3 rue des Vergers » → numéro + catégorie + nom de voie."""
    Client = apps.get_model("client", "Client")
    for client in Client.objects.exclude(adresse="").only("id", "adresse"):
        mots = client.adresse.split()
        numero = mots[0] if mots and mots[0][:1].isdigit() else ""
        type_voie, voie = split_voie(" ".join(mots[1:]) if numero else client.adresse)
        Client.objects.filter(pk=client.pk).update(
            numero_voie=numero[:10], type_voie=type_voie, voie=voie[:255]
        )


def recomposer_adresses(apps, schema_editor):
    Client = apps.get_model("client", "Client")
    libelles = dict(Client._meta.get_field("type_voie").choices or [])
    for client in Client.objects.only("id", "numero_voie", "type_voie", "voie"):
        parts = [client.numero_voie, str(libelles.get(client.type_voie, "")), client.voie]
        Client.objects.filter(pk=client.pk).update(adresse=" ".join(p for p in parts if p)[:255])


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_client_prenom'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='numero_voie',
            field=models.CharField(blank=True, max_length=10, verbose_name='n° de voie'),
        ),
        migrations.AddField(
            model_name='client',
            name='type_voie',
            field=models.CharField(blank=True, choices=[('allee', 'Allée'), ('avenue', 'Avenue'), ('boulevard', 'Boulevard'), ('carrefour', 'Carrefour'), ('chaussee', 'Chaussée'), ('chemin', 'Chemin'), ('cite', 'Cité'), ('clos', 'Clos'), ('corniche', 'Corniche'), ('cote', 'Côte'), ('cour', 'Cour'), ('cours', 'Cours'), ('descente', 'Descente'), ('domaine', 'Domaine'), ('esplanade', 'Esplanade'), ('faubourg', 'Faubourg'), ('ferme', 'Ferme'), ('grande_rue', 'Grande rue'), ('hameau', 'Hameau'), ('impasse', 'Impasse'), ('lieu_dit', 'Lieu-dit'), ('lotissement', 'Lotissement'), ('mas', 'Mas'), ('montee', 'Montée'), ('parc', 'Parc'), ('passage', 'Passage'), ('place', 'Place'), ('placette', 'Placette'), ('plaine', 'Plaine'), ('plateau', 'Plateau'), ('pont', 'Pont'), ('port', 'Port'), ('promenade', 'Promenade'), ('quai', 'Quai'), ('quartier', 'Quartier'), ('residence', 'Résidence'), ('rond_point', 'Rond-point'), ('route', 'Route'), ('rue', 'Rue'), ('ruelle', 'Ruelle'), ('sentier', 'Sentier'), ('square', 'Square'), ('traverse', 'Traverse'), ('vallon', 'Vallon'), ('villa', 'Villa'), ('village', 'Village'), ('voie', 'Voie'), ('zone', 'Zone'), ('autre', 'Autre')], max_length=20, verbose_name='catégorie de voie'),
        ),
        migrations.AddField(
            model_name='client',
            name='voie',
            field=models.CharField(blank=True, max_length=255, verbose_name='voie'),
        ),
        migrations.RunPython(decouper_adresses, recomposer_adresses),
        migrations.RemoveField(
            model_name='client',
            name='adresse',
        ),
    ]
