# Generated by Django 5.2.15 on 2026-07-27 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_remove_client_adresse_client_numero_voie_and_more'),
        ('exploitations', '0020_adresseexploitation_date_debut_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_partenaire', models.CharField(choices=[('bailleur', 'Bailleur'), ('comptable', 'Comptable'), ('avocat', 'Avocat'), ('autre', 'Autre')], default='autre', max_length=15, verbose_name='type')),
                ('nom', models.CharField(max_length=255, verbose_name='nom / raison sociale')),
                ('contact_principal', models.CharField(blank=True, max_length=255, verbose_name='contact principal')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='téléphone')),
                ('site_web', models.CharField(blank=True, max_length=255, verbose_name='site web')),
                ('numero_voie', models.CharField(blank=True, max_length=10, verbose_name='n° de voie')),
                ('type_voie', models.CharField(blank=True, choices=[('allee', 'Allée'), ('avenue', 'Avenue'), ('boulevard', 'Boulevard'), ('carrefour', 'Carrefour'), ('chaussee', 'Chaussée'), ('chemin', 'Chemin'), ('cite', 'Cité'), ('clos', 'Clos'), ('corniche', 'Corniche'), ('cote', 'Côte'), ('cour', 'Cour'), ('cours', 'Cours'), ('descente', 'Descente'), ('domaine', 'Domaine'), ('esplanade', 'Esplanade'), ('faubourg', 'Faubourg'), ('ferme', 'Ferme'), ('grande_rue', 'Grande rue'), ('hameau', 'Hameau'), ('impasse', 'Impasse'), ('lieu_dit', 'Lieu-dit'), ('lotissement', 'Lotissement'), ('mas', 'Mas'), ('montee', 'Montée'), ('parc', 'Parc'), ('passage', 'Passage'), ('place', 'Place'), ('placette', 'Placette'), ('plaine', 'Plaine'), ('plateau', 'Plateau'), ('pont', 'Pont'), ('port', 'Port'), ('promenade', 'Promenade'), ('quai', 'Quai'), ('quartier', 'Quartier'), ('residence', 'Résidence'), ('rond_point', 'Rond-point'), ('route', 'Route'), ('rue', 'Rue'), ('ruelle', 'Ruelle'), ('sentier', 'Sentier'), ('square', 'Square'), ('traverse', 'Traverse'), ('vallon', 'Vallon'), ('villa', 'Villa'), ('village', 'Village'), ('voie', 'Voie'), ('zone', 'Zone'), ('autre', 'Autre')], max_length=20, verbose_name='catégorie de voie')),
                ('voie', models.CharField(blank=True, max_length=255, verbose_name='voie')),
                ('code_postal', models.CharField(blank=True, max_length=10, verbose_name='code postal')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='ville')),
                ('siret', models.CharField(blank=True, max_length=20, verbose_name='SIRET')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partenaires', to='exploitations.exploitation')),
            ],
            options={
                'verbose_name': 'partenaire',
                'verbose_name_plural': 'partenaires',
                'ordering': ('nom',),
                'indexes': [models.Index(fields=['exploitation', 'type_partenaire'], name='client_part_exploit_094d01_idx')],
            },
        ),
    ]
