# Generated by Django 5.2.15 on 2026-08-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_partenaire_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='superpdp_adresse',
            field=models.CharField(blank=True, help_text="Identifiant d'annuaire, par exemple « 0225:315143296_68152 ».", max_length=100, verbose_name='adresse de facturation électronique'),
        ),
    ]
