# Generated by Django 5.2.15 on 2026-09-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_client_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partenaire',
            name='type_partenaire',
            field=models.CharField(choices=[('bailleur', 'Bailleur'), ('comptable', 'Comptable'), ('avocat', 'Avocat'), ('cuma', 'CUMA'), ('autre', 'Autre')], default='autre', max_length=15, verbose_name='type'),
        ),
    ]
