# Generated by Django 5.2.15 on 2026-06-23 15:16

import django.db.models.deletion
import messagerie.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagerie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='messagerie/', validators=[messagerie.models.validate_piece_jointe], verbose_name='fichier')),
                ('nom', models.CharField(max_length=255, verbose_name='nom')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='messagerie.message')),
            ],
            options={
                'verbose_name': 'pièce jointe',
                'verbose_name_plural': 'pièces jointes',
                'ordering': ('created_at',),
            },
        ),
    ]
