# Generated by Django 5.2.15 on 2026-07-25 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Espece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=255, verbose_name='nom')),
                ('nom_scientifique', models.CharField(blank=True, max_length=255, verbose_name='nom scientifique')),
                ('famille', models.CharField(choices=[('bovins', 'Bovins'), ('ovins', 'Ovins'), ('caprins', 'Caprins'), ('porcins', 'Porcins'), ('volailles', 'Volailles'), ('equides', 'Équidés'), ('lapins', 'Lapins'), ('abeilles', 'Abeilles'), ('autre', 'Autre')], default='autre', max_length=20, verbose_name='famille')),
                ('production', models.CharField(choices=[('lait', 'Lait'), ('viande', 'Viande'), ('oeufs', 'Œufs'), ('mixte', 'Mixte'), ('laine', 'Laine'), ('travail', 'Travail'), ('miel', 'Miel'), ('autre', 'Autre')], default='mixte', max_length=20, verbose_name='production')),
                ('duree_gestation_jours', models.PositiveIntegerField(blank=True, null=True, verbose_name='durée de gestation (jours)')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
            ],
            options={
                'verbose_name': 'espèce',
                'verbose_name_plural': 'espèces',
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=255, verbose_name='race')),
                ('nom_scientifique', models.CharField(blank=True, max_length=255, verbose_name='nom scientifique')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='elevage/', verbose_name='photo')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('note', models.FloatField(blank=True, null=True, verbose_name='note (/5)')),
                ('nb_avis', models.PositiveIntegerField(default=0, verbose_name="nombre d'avis")),
                ('robe', models.CharField(blank=True, max_length=255, verbose_name='robe / plumage')),
                ('poids_adulte', models.CharField(blank=True, max_length=100, verbose_name='poids adulte')),
                ('taille', models.CharField(blank=True, max_length=100, verbose_name='taille')),
                ('aptitude', models.CharField(blank=True, max_length=255, verbose_name='aptitude')),
                ('prolificite', models.CharField(blank=True, max_length=100, verbose_name='prolificité')),
                ('rusticite', models.CharField(blank=True, max_length=100, verbose_name='rusticité')),
                ('alimentation', models.CharField(blank=True, max_length=255, verbose_name='alimentation')),
                ('particularites', models.CharField(blank=True, max_length=255, verbose_name='particularités')),
                ('conseil_elevage', models.TextField(blank=True, verbose_name="conseil d'élevage")),
                ('origine', models.CharField(blank=True, max_length=255, verbose_name='origine')),
                ('origine_texte', models.TextField(blank=True, verbose_name='origine (historique)')),
                ('espece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='races', to='elevage.espece')),
            ],
            options={
                'verbose_name': 'race',
                'verbose_name_plural': 'races',
                'ordering': ('nom',),
                'indexes': [models.Index(fields=['espece'], name='elevage_rac_espece__a597b8_idx')],
            },
        ),
    ]
