# Generated by Django 5.2.15 on 2026-06-23 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exploitations', '0001_initial'),
        ('parcelles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IotDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='nom')),
                ('device_type', models.CharField(choices=[('flow_meter', 'Débitmètre'), ('pressure_sensor', 'Capteur de pression'), ('weather_station', 'Station météo'), ('valve_controller', 'Contrôleur de vanne'), ('pump_controller', 'Contrôleur de pompe'), ('soil_moisture', 'Humidité du sol'), ('energy_meter', "Compteur d'énergie"), ('generic', 'Générique')], max_length=20)),
                ('brand', models.CharField(choices=[('vyrsa', 'Vyrsa'), ('sentek', 'Sentek'), ('irrimeter', 'Irrimeter'), ('schneider', 'Schneider'), ('generic', 'Générique')], default='vyrsa', max_length=20)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('device_id', models.CharField(max_length=100, unique=True, verbose_name='identifiant device')),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_token', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('online', 'En ligne'), ('offline', 'Hors ligne'), ('warning', 'Avertissement'), ('error', 'Erreur')], default='offline', max_length=10)),
                ('config', models.JSONField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('firmware_version', models.CharField(blank=True, max_length=50)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='exploitations.exploitation')),
                ('parcelle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='parcelles.parcelle')),
            ],
            options={
                'verbose_name': 'device IoT',
                'verbose_name_plural': 'devices IoT',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='IotCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_type', models.CharField(max_length=100)),
                ('parameters', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyée'), ('acknowledged', 'Accusée'), ('completed', 'Terminée'), ('failed', 'Échouée'), ('expired', 'Expirée')], default='pending', max_length=15)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='iot.iotdevice')),
            ],
            options={
                'verbose_name': 'commande IoT',
                'verbose_name_plural': 'commandes IoT',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('threshold_type', models.CharField(choices=[('frost_temperature', 'Température gel'), ('min_pressure', 'Pression min'), ('max_pressure', 'Pression max'), ('min_flow', 'Débit min'), ('max_flow', 'Débit max'), ('max_kwh_m3', 'kWh/m³ max'), ('soil_moisture_min', 'Humidité sol min'), ('soil_moisture_max', 'Humidité sol max'), ('invisible_loss_pct', 'Perte invisible %')], max_length=20)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iot.iotdevice')),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='exploitations.exploitation')),
                ('parcelle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parcelles.parcelle')),
            ],
            options={
                'verbose_name': 'seuil',
                'verbose_name_plural': 'seuils',
            },
        ),
        migrations.CreateModel(
            name='IotAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('leak_detected', 'Fuite détectée'), ('low_pressure', 'Pression basse'), ('high_pressure', 'Pression haute'), ('low_flow', 'Débit bas'), ('high_flow', 'Débit élevé'), ('pump_failure', 'Panne de pompe'), ('uniformity_drop', "Baisse d'uniformité"), ('energy_spike', "Pic d'énergie"), ('offline', 'Hors ligne'), ('threshold_exceeded', 'Seuil dépassé'), ('frost_risk', 'Risque de gel'), ('invisible_loss', 'Perte invisible')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Avertissement'), ('danger', 'Danger')], default='warning', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('threshold_value', models.FloatField(blank=True, null=True)),
                ('actual_value', models.FloatField(blank=True, null=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='exploitations.exploitation')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='iot.iotdevice')),
            ],
            options={
                'verbose_name': 'alerte IoT',
                'verbose_name_plural': 'alertes IoT',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['exploitation', '-created_at'], name='iot_iotaler_exploit_64795f_idx')],
            },
        ),
        migrations.CreateModel(
            name='IotTelemetry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=None, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('primary_value', models.FloatField(blank=True, null=True)),
                ('primary_unit', models.CharField(blank=True, max_length=50)),
                ('flow_rate_m3h', models.FloatField(blank=True, null=True)),
                ('pressure_bar', models.FloatField(blank=True, null=True)),
                ('power_kw', models.FloatField(blank=True, null=True)),
                ('energy_kwh', models.FloatField(blank=True, null=True)),
                ('soil_moisture', models.FloatField(blank=True, null=True)),
                ('signal_strength', models.IntegerField(blank=True, null=True)),
                ('battery_level', models.IntegerField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='iot.iotdevice')),
            ],
            options={
                'verbose_name': 'télémétrie',
                'verbose_name_plural': 'télémétries',
                'ordering': ('-timestamp',),
                'indexes': [models.Index(fields=['device', '-timestamp'], name='iot_iottele_device__e2efad_idx')],
            },
        ),
    ]
