# Generated by Django 5.2.15 on 2026-06-24 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exploitations', '0001_initial'),
        ('parcelles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyseSol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('ph', models.FloatField(blank=True, null=True)),
                ('ec', models.FloatField(blank=True, null=True)),
                ('azote_total', models.FloatField(blank=True, null=True)),
                ('phosphore_assimilable', models.FloatField(blank=True, null=True)),
                ('potassium_echangeable', models.FloatField(blank=True, null=True)),
                ('matiere_organique', models.FloatField(blank=True, null=True)),
                ('calcaire_total', models.FloatField(blank=True, null=True)),
                ('laboratoire', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses_sol', to='exploitations.exploitation')),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses_sol', to='parcelles.parcelle')),
            ],
            options={
                'verbose_name': 'analyse de sol',
                'verbose_name_plural': 'analyses de sol',
                'ordering': ('-date',),
            },
        ),
    ]
