# Generated by Django 5.2.15 on 2026-06-25 07:27

import analyse_sol.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse_sol', '0002_analysesol_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysesol',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=analyse_sol.models.document_upload_path, verbose_name='document'),
        ),
    ]
