# Generated by Django 5.2.15 on 2026-07-17 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse_sol', '0003_alter_analysesol_document'),
        ('exploitations', '0006_rename_telephone_fields'),
        ('parcelles', '0002_parcelle_acquired_at_parcelle_cadastre_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='nom')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('specialites', models.CharField(blank=True, help_text='ex : analyses physico-chimiques, reliquats azotés, oligo-éléments', max_length=255, verbose_name='spécialités')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='région')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='téléphone')),
                ('site_web', models.URLField(blank=True, verbose_name='site web')),
                ('delai_jours', models.PositiveIntegerField(blank=True, null=True, verbose_name='délai indicatif (jours)')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'laboratoire partenaire',
                'verbose_name_plural': 'laboratoires partenaires',
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='DemandeAnalyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_analyse', models.CharField(choices=[('complete', 'Analyse complète (physico-chimique)'), ('base', 'Analyse de base (pH, MO, N-P-K)'), ('reliquat', 'Reliquat azoté'), ('oligo', 'Oligo-éléments'), ('matiere_organique', 'Matière organique'), ('autre', 'Autre')], default='complete', max_length=20, verbose_name="type d'analyse")),
                ('statut', models.CharField(choices=[('envoyee', 'Envoyée'), ('en_cours', 'En cours'), ('recue', 'Reçue'), ('annulee', 'Annulée')], default='envoyee', max_length=10, verbose_name='statut')),
                ('message', models.TextField(blank=True, verbose_name='message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analyse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demande', to='analyse_sol.analysesol')),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_analyse', to='exploitations.exploitation')),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_analyse', to='parcelles.parcelle')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('laboratoire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to='analyse_sol.laboratoire')),
            ],
            options={
                'verbose_name': "demande d'analyse",
                'verbose_name_plural': "demandes d'analyse",
                'ordering': ('-created_at',),
            },
        ),
    ]
