# Generated by Django 5.2.15 on 2026-07-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse_sol', '0004_laboratoire_demandeanalyse'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysesol',
            name='aluminium_echangeable',
            field=models.FloatField(blank=True, null=True, verbose_name='aluminium échangeable (mg/kg sec)'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='aluminium_total',
            field=models.FloatField(blank=True, null=True, verbose_name='aluminium total (% sec)'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='argile',
            field=models.FloatField(blank=True, null=True, verbose_name='argile (%)'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='arsenic',
            field=models.FloatField(blank=True, null=True, verbose_name='arsenic total (mg/kg MS)'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='azote_ammoniacal',
            field=models.FloatField(blank=True, null=True, verbose_name='azote ammoniacal N-NH4 (mg/kg)'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='bore',
            field=models.FloatField(blank=True, null=True, verbose_name='bore B (mg/kg)'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='bore_total',
            field=models.FloatField(blank=True, null=True, verbose_name='bore total (mg/kg sec)'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='c_n',
            field=models.FloatField(blank=True, null=True, verbose_name='rapport C/N'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='ca_cec',
            field=models.FloatField(blank=True, null=True, verbose_name='Ca/CEC (%)'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='cadmium',
            field=models.FloatField(blank=True, null=True, verbose_name='cadmium (mg/kg MS)'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='calcaire_actif',
            field=models.FloatField(blank=True, null=True, verbose_name='calcaire actif (% sec)'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='calcium_cao',
            field=models.FloatField(blank=True, null=True, verbose_name='calcium CaO (mg/kg)'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='capacite_retention_pf25',
            field=models.FloatField(blank=True, null=True, verbose_name='rétention en eau à pF 2.5 (% MS)'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='capacite_retention_pf42',
            field=models.FloatField(blank=True, null=True, verbose_name='rétention en eau à pF 4.2 (% MS)'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='carbone_organique',
            field=models.FloatField(blank=True, null=True, verbose_name='carbone organique (%)'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='cec',
            field=models.FloatField(blank=True, null=True, verbose_name='CEC (meq/100g)'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='chrome',
            field=models.FloatField(blank=True, null=True, verbose_name='chrome (mg/kg MS)'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='cobalt',
            field=models.FloatField(blank=True, null=True, verbose_name='cobalt (mg/kg sec)'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='coefficient_k2',
            field=models.FloatField(blank=True, null=True, verbose_name='coefficient K2 (%)'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='commune',
            field=models.CharField(blank=True, max_length=255, verbose_name='commune'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='cuivre',
            field=models.FloatField(blank=True, null=True, verbose_name='cuivre Cu EDTA (mg/kg)'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='cuivre_total',
            field=models.FloatField(blank=True, null=True, verbose_name='cuivre total (mg/kg MS)'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='date_arrivee_labo',
            field=models.DateField(blank=True, null=True, verbose_name='arrivée labo'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='date_expedition',
            field=models.DateField(blank=True, null=True, verbose_name='sortie labo'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='date_prelevement',
            field=models.DateField(blank=True, null=True, verbose_name='prélevé le'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='densite_apparente',
            field=models.FloatField(blank=True, null=True, verbose_name='densité apparente (g/cm³)'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='fer',
            field=models.FloatField(blank=True, null=True, verbose_name='fer Fe EDTA (mg/kg)'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='fer_total',
            field=models.FloatField(blank=True, null=True, verbose_name='fer total (% sec)'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='h_cec',
            field=models.FloatField(blank=True, null=True, verbose_name='H/CEC (%)'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='humidite',
            field=models.FloatField(blank=True, null=True, verbose_name='humidité sur brut (%)'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='indice_battance',
            field=models.FloatField(blank=True, null=True, verbose_name='indice de battance'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='k_cec',
            field=models.FloatField(blank=True, null=True, verbose_name='K/CEC (%)'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='limons_fins',
            field=models.FloatField(blank=True, null=True, verbose_name='limons fins (%)'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='limons_grossiers',
            field=models.FloatField(blank=True, null=True, verbose_name='limons grossiers (%)'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='magnesium_mgo',
            field=models.FloatField(blank=True, null=True, verbose_name='magnésie MgO (mg/kg)'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='manganese',
            field=models.FloatField(blank=True, null=True, verbose_name='manganèse Mn EDTA (mg/kg)'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='manganese_total',
            field=models.FloatField(blank=True, null=True, verbose_name='manganèse total (mg/kg sec)'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='matiere_seche',
            field=models.FloatField(blank=True, null=True, verbose_name='matière sèche sur brut (%)'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='mercure',
            field=models.FloatField(blank=True, null=True, verbose_name='mercure (mg/kg MS)'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='mg_cec',
            field=models.FloatField(blank=True, null=True, verbose_name='Mg/CEC (%)'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='molybdene',
            field=models.FloatField(blank=True, null=True, verbose_name='molybdène total (mg/kg sec)'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='na_cec',
            field=models.FloatField(blank=True, null=True, verbose_name='Na/CEC (%)'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='nickel',
            field=models.FloatField(blank=True, null=True, verbose_name='nickel (mg/kg MS)'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='numero_laboratoire',
            field=models.CharField(blank=True, max_length=50, verbose_name='n° laboratoire'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='ph_kcl',
            field=models.FloatField(blank=True, null=True, verbose_name='pH KCl'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='phosphore_olsen',
            field=models.FloatField(blank=True, null=True, verbose_name='phosphore Olsen (mg/kg)'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='plomb',
            field=models.FloatField(blank=True, null=True, verbose_name='plomb (mg/kg MS)'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='profondeur_prelevement',
            field=models.CharField(blank=True, max_length=50, verbose_name='profondeur de prélèvement'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='reference',
            field=models.CharField(blank=True, max_length=255, verbose_name='référence'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='refus_2mm',
            field=models.FloatField(blank=True, null=True, verbose_name='refus à 2 mm (%)'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='reserve_facilement_utilisable',
            field=models.FloatField(blank=True, null=True, verbose_name='réserve facilement utilisable RFU (mm/cm)'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='reserve_utile',
            field=models.FloatField(blank=True, null=True, verbose_name='réserve utile RU (mm/cm)'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='risque_battance',
            field=models.CharField(blank=True, max_length=50, verbose_name='risque de battance'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='sables_fins',
            field=models.FloatField(blank=True, null=True, verbose_name='sables fins (%)'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='sables_grossiers',
            field=models.FloatField(blank=True, null=True, verbose_name='sables grossiers (%)'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='selenium',
            field=models.FloatField(blank=True, null=True, verbose_name='sélénium total (mg/kg sec)'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='sodium_na2o',
            field=models.FloatField(blank=True, null=True, verbose_name='sodium Na2O (mg/kg)'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='somme_16_hap',
            field=models.CharField(blank=True, max_length=50, verbose_name='somme 16 HAP (mg/kg MS)'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='somme_7_pcb',
            field=models.CharField(blank=True, max_length=50, verbose_name='somme 7 PCB (mg/kg MS)'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='taux_saturation',
            field=models.CharField(blank=True, max_length=20, verbose_name='taux de saturation (%)'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='technicien',
            field=models.CharField(blank=True, max_length=255, verbose_name='technicien'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='type_sol',
            field=models.CharField(blank=True, max_length=100, verbose_name='type de sol'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='zinc',
            field=models.FloatField(blank=True, null=True, verbose_name='zinc Zn EDTA (mg/kg)'),
        ),
        migrations.AddField(
            model_name='analysesol',
            name='zinc_total',
            field=models.FloatField(blank=True, null=True, verbose_name='zinc total (mg/kg MS)'),
        ),
        migrations.AlterField(
            model_name='analysesol',
            name='azote_total',
            field=models.FloatField(blank=True, null=True, verbose_name='azote total N (%)'),
        ),
        migrations.AlterField(
            model_name='analysesol',
            name='calcaire_total',
            field=models.FloatField(blank=True, null=True, verbose_name='calcaire total (%)'),
        ),
        migrations.AlterField(
            model_name='analysesol',
            name='ec',
            field=models.FloatField(blank=True, null=True, verbose_name='conductivité (mS/cm)'),
        ),
        migrations.AlterField(
            model_name='analysesol',
            name='laboratoire',
            field=models.CharField(blank=True, max_length=255, verbose_name='laboratoire'),
        ),
        migrations.AlterField(
            model_name='analysesol',
            name='matiere_organique',
            field=models.FloatField(blank=True, null=True, verbose_name='matière organique (%)'),
        ),
        migrations.AlterField(
            model_name='analysesol',
            name='ph',
            field=models.FloatField(blank=True, null=True, verbose_name='pH eau'),
        ),
        migrations.AlterField(
            model_name='analysesol',
            name='phosphore_assimilable',
            field=models.FloatField(blank=True, null=True, verbose_name='phosphore P2O5 (mg/kg)'),
        ),
        migrations.AlterField(
            model_name='analysesol',
            name='potassium_echangeable',
            field=models.FloatField(blank=True, null=True, verbose_name='potasse K2O (mg/kg)'),
        ),
    ]
