# Generated by Django 5.2.15 on 2026-06-23 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agronomie', '0002_fertigation'),
        ('exploitations', '0001_initial'),
        ('parcelles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyseSol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('ph', models.FloatField(blank=True, null=True)),
                ('ec', models.FloatField(blank=True, null=True)),
                ('azote_total', models.FloatField(blank=True, null=True)),
                ('phosphore_assimilable', models.FloatField(blank=True, null=True)),
                ('potassium_echangeable', models.FloatField(blank=True, null=True)),
                ('matiere_organique', models.FloatField(blank=True, null=True)),
                ('calcaire_total', models.FloatField(blank=True, null=True)),
                ('laboratoire', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses_sol', to='exploitations.exploitation')),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses_sol', to='parcelles.parcelle')),
            ],
            options={
                'verbose_name': 'analyse de sol',
                'verbose_name_plural': 'analyses de sol',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('soil', 'Sol'), ('water', 'Eau'), ('leaf', 'Foliaire'), ('plant', 'Plante')], max_length=10)),
                ('sample_date', models.DateTimeField()),
                ('lab_name', models.CharField(blank=True, max_length=255)),
                ('file_url', models.TextField(blank=True)),
                ('file_key', models.TextField(blank=True)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('ocr_raw_text', models.TextField(blank=True)),
                ('parsed_data', models.JSONField(blank=True, null=True)),
                ('ph', models.FloatField(blank=True, null=True)),
                ('organic_matter_pct', models.FloatField(blank=True, null=True)),
                ('nitrogen_mg_kg', models.FloatField(blank=True, null=True)),
                ('phosphorus_mg_kg', models.FloatField(blank=True, null=True)),
                ('potassium_mg_kg', models.FloatField(blank=True, null=True)),
                ('electrical_conductivity', models.FloatField(blank=True, null=True)),
                ('recommendations', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending_ocr', 'OCR en attente'), ('ocr_done', 'OCR effectué'), ('validated', 'Validé')], default='pending_ocr', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='exploitations.exploitation')),
                ('parcelle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parcelles.parcelle')),
            ],
            options={
                'verbose_name': "rapport d'analyse",
                'verbose_name_plural': "rapports d'analyse",
                'ordering': ('-sample_date',),
            },
        ),
        migrations.CreateModel(
            name='BiodiversiteFiche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('nb_especes_vegetales', models.IntegerField(default=0)),
                ('nb_especes_animales', models.IntegerField(default=0)),
                ('haies_ml', models.FloatField(default=0)),
                ('jachere_ha', models.FloatField(default=0)),
                ('observations', models.TextField(blank=True)),
                ('date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biodiversite_fiches', to='exploitations.exploitation')),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biodiversite_fiches', to='parcelles.parcelle')),
                ('saison', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agronomie.saison')),
            ],
            options={
                'verbose_name': 'fiche biodiversité',
                'verbose_name_plural': 'fiches biodiversité',
                'ordering': ('-date',),
            },
        ),
    ]
