# Generated by Django 5.2.15 on 2026-06-24 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalyseSol',
        ),
    ]
