# Generated by Django 5.2.15 on 2026-07-25 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0002_delete_analysesol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biodiversitefiche',
            name='saison',
        ),
    ]
