from django.urls import path

from . import views

app_name = "contrat"

urlpatterns = [
    path("contrats/", views.contrats, name="contrats"),
    path("contrats/nouveau/", views.contrat_create, name="create"),
    path("contrats/<int:pk>/supprimer/", views.contrat_delete, name="delete"),
    path("baux/", views.baux, name="baux"),
    path("baux/nouveau/", views.bail_create, name="bail_create"),
    path("baux/<int:pk>/enregistrer/", views.bail_create, name="bail_edit"),
    path("baux/<int:pk>/supprimer/", views.bail_delete, name="bail_delete"),
    path("baux/scanner/", views.bail_scanner, name="bail_scanner"),
    path("baux/<int:pk>/document/", views.bail_document, name="bail_document"),
    path("baux/document/<int:pk>/supprimer/", views.bail_document_delete,
         name="bail_document_delete"),
    path("actes-notaries/", views.actes_notaries, name="actes"),
    path("actes-notaries/nouveau/", views.acte_create, name="acte_create"),
    path("actes-notaries/<int:pk>/enregistrer/", views.acte_create, name="acte_edit"),
    path("actes-notaries/<int:pk>/supprimer/", views.acte_delete, name="acte_delete"),
    path("actes-notaries/scanner/", views.acte_scanner, name="acte_scanner"),
    path("actes-notaries/<int:pk>/document/", views.acte_document, name="acte_document"),
    path("actes-notaries/document/<int:pk>/supprimer/", views.acte_document_delete,
         name="acte_document_delete"),
    path("assurances/", views.assurances, name="assurances"),
    path("assurances/nouvelle/", views.assurance_create, name="assurance_create"),
    path("assurances/<int:pk>/enregistrer/", views.assurance_create, name="assurance_edit"),
    path("assurances/<int:pk>/supprimer/", views.assurance_delete, name="assurance_delete"),
    path("assurances/scanner/", views.assurance_scanner, name="assurance_scanner"),
    path("assurances/<int:pk>/document/", views.assurance_document, name="assurance_document"),
    path("assurances/document/<int:pk>/supprimer/", views.assurance_document_delete,
         name="assurance_document_delete"),
    path("assurances/rendez-vous/", views.rendez_vous_create, name="rendez_vous_create"),
    path("msa/", views.msa, name="msa"),
    path("msa/nouvelle/", views.msa_create, name="msa_create"),
    path("msa/<int:pk>/supprimer/", views.msa_delete, name="msa_delete"),
    # ── Drive ──
    path("drive/", views.drive, name="drive"),
    path("drive/dossier/<int:pk>/", views.drive, name="drive_dossier"),
    path("drive/nouveau-dossier/", views.drive_dossier_creer, name="drive_dossier_creer"),
    path("drive/dossier/<int:pk>/nouveau-dossier/", views.drive_dossier_creer,
         name="drive_sous_dossier_creer"),
    path("drive/dossier/<int:pk>/renommer/", views.drive_dossier_renommer,
         name="drive_dossier_renommer"),
    path("drive/dossier/<int:pk>/supprimer/", views.drive_dossier_supprimer,
         name="drive_dossier_supprimer"),
    path("drive/importer/", views.drive_deposer, name="drive_deposer"),
    path("drive/dossier/<int:pk>/importer/", views.drive_deposer, name="drive_deposer_dans"),
    path("drive/fichier/<int:pk>/renommer/", views.drive_fichier_renommer,
         name="drive_fichier_renommer"),
    path("drive/fichier/<int:pk>/supprimer/", views.drive_fichier_supprimer,
         name="drive_fichier_supprimer"),
    path("drive/<int:pk>/deplacer/", views.drive_deplacer, name="drive_deplacer"),
]
