# Generated by Django 5.2.15 on 2026-08-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_address_city_user_address_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profil_souhaite',
            field=models.CharField(blank=True, max_length=20, verbose_name='profil déclaré'),
        ),
    ]
