# Generated by Django 5.2.15 on 2026-07-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planningtask',
            name='type',
            field=models.CharField(choices=[('irrigation', 'Irrigation'), ('traitement', 'Traitement'), ('fertilisation', 'Fertilisation'), ('recolte', 'Récolte'), ('semis', 'Semis'), ('travail_sol', 'Travail du sol'), ('taille', 'Taille'), ('maintenance', 'Maintenance'), ('observation', 'Observation'), ('chantier', 'Chantier'), ('depannage', 'Dépannage'), ('rendez_vous', 'Rendez-vous'), ('autre', 'Autre')], default='autre', max_length=20),
        ),
    ]
