# Generated by Django 5.2.15 on 2026-09-02 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exploitations', '0021_exploitation_logo'),
        ('planning', '0002_alter_planningtask_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccesPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('niveau', models.CharField(choices=[('lecture', 'Lecture'), ('ecriture', 'Écriture'), ('gestion', 'Gestion des accès')], default='lecture', max_length=10, verbose_name='niveau')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('accorde', 'Accordé'), ('refuse', 'Refusé')], default='en_attente', max_length=10, verbose_name='statut')),
                ('message', models.TextField(blank=True, verbose_name='message')),
                ('decide_le', models.DateTimeField(blank=True, null=True, verbose_name='décidé le')),
                ('decide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acces_planning_decides', to=settings.AUTH_USER_MODEL, verbose_name='décidé par')),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acces_planning', to='exploitations.exploitation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acces_planning', to=settings.AUTH_USER_MODEL, verbose_name='compte')),
            ],
            options={
                'verbose_name': 'accès au planning',
                'verbose_name_plural': 'accès au planning',
                'ordering': ('statut', 'user_id'),
                'constraints': [models.UniqueConstraint(fields=('exploitation', 'user'), name='un_seul_acces_planning_par_compte')],
            },
        ),
    ]
