# Generated by Django 5.2.15 on 2026-09-02 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_accesplanning'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlanningAccess',
        ),
    ]
