# Generated by Django 5.2.15 on 2026-06-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('associe', 'Associé'), ('chef', "Chef d'équipe"), ('ouvrier', 'Ouvrier'), ('saisonnier', 'Saisonnier'), ('prestataire', 'Prestataire')], default='ouvrier', max_length=12),
        ),
    ]
