# Generated by Django 5.2.15 on 2026-07-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0002_alter_teammember_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='color',
            field=models.CharField(default='#29738f', max_length=7),
        ),
    ]
