# Generated by Django 5.2.15 on 2026-08-21 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0003_alter_teammember_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='password_hash',
        ),
    ]
