# Generated by Django 5.2.15 on 2026-08-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0004_remove_teammember_password_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='invitation_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='invitation acceptée le'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='invitation_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='invitation envoyée le'),
        ),
    ]
