# Generated by Django 5.2.15 on 2026-08-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0006_task_parent_task_start_date'),
        ('parcelles', '0009_parcelle_orientation_rangs'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='parcelles',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='parcelles.parcelle', verbose_name='parcelles'),
        ),
    ]
