# Generated by Django 5.2.15 on 2026-09-02 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0008_task_parcelles_depuis_parcelle'),
        ('exploitations', '0021_exploitation_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeleContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=255, verbose_name='nom du modèle')),
                ('type_contrat', models.CharField(choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('saisonnier', 'Contrat saisonnier'), ('apprentissage', "Contrat d'apprentissage"), ('professionnalisation', 'Contrat de professionnalisation'), ('stage', 'Convention de stage'), ('tesa', 'TESA — titre emploi simplifié agricole'), ('autre', 'Autre')], default='cdi', max_length=25, verbose_name='type')),
                ('corps', models.TextField(verbose_name='corps du contrat')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modeles_contrat', to='exploitations.exploitation')),
            ],
            options={
                'verbose_name': 'modèle de contrat',
                'verbose_name_plural': 'modèles de contrat',
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='ContratTravail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_contrat', models.CharField(choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('saisonnier', 'Contrat saisonnier'), ('apprentissage', "Contrat d'apprentissage"), ('professionnalisation', 'Contrat de professionnalisation'), ('stage', 'Convention de stage'), ('tesa', 'TESA — titre emploi simplifié agricole'), ('autre', 'Autre')], default='cdi', max_length=25, verbose_name='type')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('etabli', 'Établi'), ('signe', 'Signé'), ('termine', 'Terminé')], default='brouillon', max_length=12, verbose_name='statut')),
                ('poste', models.CharField(blank=True, max_length=255, verbose_name='poste')),
                ('lieu', models.CharField(blank=True, max_length=255, verbose_name='lieu de travail')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='date de fin')),
                ('duree_hebdo', models.FloatField(blank=True, null=True, verbose_name='durée hebdomadaire (h)')),
                ('remuneration', models.FloatField(blank=True, null=True, verbose_name='rémunération brute mensuelle')),
                ('date_signature', models.DateField(blank=True, null=True, verbose_name='date de signature')),
                ('corps', models.TextField(blank=True, verbose_name='corps du contrat')),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats_travail', to='exploitations.exploitation')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='equipe.teammember', verbose_name='salarié')),
                ('modele', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipe.modelecontrat', verbose_name="modèle d'origine")),
            ],
            options={
                'verbose_name': 'contrat de travail',
                'verbose_name_plural': 'contrats de travail',
                'ordering': ('-date_debut', '-created_at'),
                'indexes': [models.Index(fields=['exploitation', 'statut'], name='equipe_cont_exploit_7d3192_idx')],
            },
        ),
    ]
