# Generated by Django 5.2.15 on 2026-09-02 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0009_modelecontrat_contrattravail'),
        ('exploitations', '0021_exploitation_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffreEmploi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titre', models.CharField(max_length=255, verbose_name='intitulé du poste')),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True, verbose_name='adresse publique')),
                ('type_contrat', models.CharField(choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('saisonnier', 'Contrat saisonnier'), ('apprentissage', "Contrat d'apprentissage"), ('professionnalisation', 'Contrat de professionnalisation'), ('stage', 'Convention de stage'), ('tesa', 'TESA — titre emploi simplifié agricole'), ('autre', 'Autre')], default='saisonnier', max_length=25, verbose_name='type de contrat')),
                ('description', models.TextField(verbose_name='description du poste')),
                ('profil', models.TextField(blank=True, verbose_name='profil recherché')),
                ('lieu', models.CharField(blank=True, max_length=255, verbose_name='lieu de travail')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='prise de poste')),
                ('duree_hebdo', models.FloatField(blank=True, null=True, verbose_name='durée hebdomadaire (h)')),
                ('remuneration', models.CharField(blank=True, max_length=255, verbose_name='rémunération')),
                ('logement', models.BooleanField(default=False, verbose_name='logement possible')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='email de contact')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publiee', 'Publiée'), ('pourvue', 'Pourvue'), ('close', 'Close')], default='brouillon', max_length=10, verbose_name='statut')),
                ('publiee_le', models.DateTimeField(blank=True, null=True, verbose_name='publiée le')),
                ('expire_le', models.DateField(blank=True, null=True, verbose_name="visible jusqu'au")),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres_emploi', to='exploitations.exploitation')),
            ],
            options={
                'verbose_name': "offre d'emploi",
                'verbose_name_plural': "offres d'emploi",
                'ordering': ('-publiee_le', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=255, verbose_name='nom')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='téléphone')),
                ('message', models.TextField(blank=True, verbose_name='message')),
                ('cv', models.FileField(blank=True, upload_to='candidatures/%Y/%m/', verbose_name='CV')),
                ('statut', models.CharField(choices=[('recue', 'Reçue'), ('vue', 'Vue'), ('retenue', 'Retenue'), ('refusee', 'Refusée')], default='recue', max_length=10, verbose_name='statut')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='equipe.offreemploi')),
            ],
            options={
                'verbose_name': 'candidature',
                'verbose_name_plural': 'candidatures',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='offreemploi',
            index=models.Index(fields=['statut', 'publiee_le'], name='equipe_offr_statut_259a3a_idx'),
        ),
    ]
