# Generated by Django 5.2.15 on 2026-09-02 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0010_offreemploi_candidature_and_more'),
        ('exploitations', '0021_exploitation_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichePaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('periode_debut', models.DateField(verbose_name='période du')),
                ('periode_fin', models.DateField(verbose_name='période au')),
                ('heures_travaillees', models.FloatField(blank=True, null=True, verbose_name='heures travaillées')),
                ('heures_supplementaires', models.FloatField(blank=True, null=True, verbose_name='heures supplémentaires')),
                ('salaire_brut', models.FloatField(default=0, verbose_name='salaire brut')),
                ('cotisations_salariales', models.FloatField(default=0, verbose_name='cotisations salariales')),
                ('cotisations_patronales', models.FloatField(default=0, verbose_name='cotisations patronales')),
                ('net_imposable', models.FloatField(blank=True, null=True, verbose_name='net imposable')),
                ('net_a_payer', models.FloatField(default=0, verbose_name='net à payer')),
                ('date_paiement', models.DateField(blank=True, null=True, verbose_name='payée le')),
                ('mode_paiement', models.CharField(blank=True, max_length=60, verbose_name='mode de paiement')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('emise', 'Émise'), ('payee', 'Payée')], default='brouillon', max_length=10, verbose_name='statut')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('contrat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_paie', to='equipe.contrattravail', verbose_name='contrat')),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_paie', to='exploitations.exploitation')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_paie', to='equipe.teammember', verbose_name='salarié')),
            ],
            options={
                'verbose_name': 'fiche de paie',
                'verbose_name_plural': 'fiches de paie',
                'ordering': ('-periode_debut', 'membre__name'),
            },
        ),
        migrations.CreateModel(
            name='LignePaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255, verbose_name='libellé')),
                ('base', models.FloatField(blank=True, null=True, verbose_name='base')),
                ('taux', models.FloatField(blank=True, null=True, verbose_name='taux (%)')),
                ('part_salariale', models.FloatField(blank=True, null=True, verbose_name='part salariale')),
                ('part_patronale', models.FloatField(blank=True, null=True, verbose_name='part patronale')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='equipe.fichepaie')),
            ],
            options={
                'verbose_name': 'ligne de paie',
                'verbose_name_plural': 'lignes de paie',
                'ordering': ('ordre', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='fichepaie',
            index=models.Index(fields=['exploitation', 'periode_debut'], name='equipe_fich_exploit_6f062a_idx'),
        ),
        migrations.AddConstraint(
            model_name='fichepaie',
            constraint=models.UniqueConstraint(fields=('membre', 'periode_debut', 'periode_fin'), name='une_fiche_par_salarie_et_periode'),
        ),
    ]
