# Generated by Django 5.2.15 on 2026-09-03 19:44

import django.db.models.deletion
from django.db import migrations, models


def signer_les_contrats_existants(apps, schema_editor):
    """Les contrats d'avant portaient la signature par défaut de la ferme.

    Le PDF la lisait alors dans la section Identité. Maintenant qu'elle est
    choisie contrat par contrat, un champ vide veut dire « pas de signature » :
    il faut donc inscrire dans l'existant ce qui s'y appliquait déjà, sans
    quoi un contrat déjà remis ressortirait non signé.
    """
    Contrat = apps.get_model("equipe", "ContratTravail")
    Piece = apps.get_model("identite", "Piece")
    for contrat in Contrat.objects.filter(signature__isnull=True):
        signatures = Piece.objects.filter(exploitation_id=contrat.exploitation_id,
                                          type_piece="signature")
        piece = (signatures.filter(par_defaut=True).first()
                 or signatures.order_by("-created_at").first())
        if piece:
            contrat.signature_id = piece.pk
            contrat.save(update_fields=["signature"])


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0011_fichepaie_lignepaie_and_more'),
        ('identite', '0003_piece_par_defaut'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrattravail',
            name='signature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrats_signes', to='identite.piece', verbose_name="signature de l'employeur"),
        ),
        migrations.RunPython(signer_les_contrats_existants,
                             migrations.RunPython.noop),
    ]
