# Generated by Django 5.2.15 on 2026-06-24 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exploitations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleveMeteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieu', models.CharField(blank=True, max_length=255, verbose_name='lieu')),
                ('latitude', models.FloatField(verbose_name='latitude')),
                ('longitude', models.FloatField(verbose_name='longitude')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='température (°C)')),
                ('humidite', models.FloatField(blank=True, null=True, verbose_name='humidité (%)')),
                ('vent', models.FloatField(blank=True, null=True, verbose_name='vent (km/h)')),
                ('pluie', models.FloatField(blank=True, null=True, verbose_name='pluie (mm)')),
                ('et0', models.FloatField(blank=True, null=True, verbose_name='ET0 (mm)')),
                ('libelle', models.CharField(blank=True, max_length=100, verbose_name='conditions')),
                ('captured_at', models.DateTimeField(auto_now_add=True, verbose_name='capturé le')),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releves_meteo', to='exploitations.exploitation')),
            ],
            options={
                'verbose_name': 'relevé météo',
                'verbose_name_plural': 'relevés météo',
                'ordering': ('-captured_at',),
            },
        ),
    ]
