# Generated by Django 5.2.15 on 2026-06-24 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exploitations', '0001_initial'),
        ('meteo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VilleMeteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='nom')),
                ('latitude', models.FloatField(verbose_name='latitude')),
                ('longitude', models.FloatField(verbose_name='longitude')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villes_meteo', to='exploitations.exploitation')),
            ],
            options={
                'verbose_name': 'ville météo',
                'verbose_name_plural': 'villes météo',
                'ordering': ('nom',),
                'unique_together': {('exploitation', 'nom')},
            },
        ),
    ]
