# Generated by Django 5.2.15 on 2026-06-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exploitations', '0001_initial'),
        ('meteo', '0002_villemeteo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='villemeteo',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='villemeteo',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, verbose_name='slug'),
        ),
        migrations.AlterUniqueTogether(
            name='villemeteo',
            unique_together={('exploitation', 'slug')},
        ),
    ]
