# Generated by Django 5.2.15 on 2026-06-24 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exploitations', '0001_initial'),
        ('meteo', '0003_alter_villemeteo_unique_together_villemeteo_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptureMeteoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='activée')),
                ('frequence_heures', models.PositiveIntegerField(choices=[(1, 'Toutes les heures'), (6, 'Toutes les 6 heures'), (12, 'Toutes les 12 heures'), (24, 'Quotidienne')], default=24, verbose_name='fréquence')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='dernière exécution')),
                ('exploitation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capture_meteo_config', to='exploitations.exploitation')),
            ],
            options={
                'verbose_name': 'planning de capture météo',
                'verbose_name_plural': 'plannings de capture météo',
            },
        ),
    ]
