# Generated by Django 5.2.15 on 2026-06-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteo', '0004_capturemeteoconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='villemeteo',
            name='capture_auto',
            field=models.BooleanField(default=False, verbose_name='capture automatique'),
        ),
        migrations.AddField(
            model_name='villemeteo',
            name='capture_frequence',
            field=models.PositiveIntegerField(choices=[(1, 'Toutes les heures'), (6, 'Toutes les 6 heures'), (12, 'Toutes les 12 heures'), (24, 'Quotidienne')], default=24, verbose_name='fréquence'),
        ),
        migrations.AddField(
            model_name='villemeteo',
            name='capture_last_run',
            field=models.DateTimeField(blank=True, null=True, verbose_name='dernière capture auto'),
        ),
        migrations.DeleteModel(
            name='CaptureMeteoConfig',
        ),
    ]
