# Generated by Django 5.2.15 on 2026-08-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteo', '0005_villemeteo_capture_auto_villemeteo_capture_frequence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='villemeteo',
            name='capture_heure_debut',
            field=models.PositiveSmallIntegerField(default=6, help_text="Heure d'ancrage des créneaux (0–23).", verbose_name='première capture de la journée'),
        ),
        migrations.AlterField(
            model_name='villemeteo',
            name='capture_auto',
            field=models.BooleanField(default=True, verbose_name='capture automatique'),
        ),
        migrations.AlterField(
            model_name='villemeteo',
            name='capture_frequence',
            field=models.PositiveIntegerField(choices=[(1, 'Toutes les heures'), (6, 'Toutes les 6 heures'), (12, 'Toutes les 12 heures'), (24, 'Quotidienne')], default=12, verbose_name='fréquence'),
        ),
    ]
