# Generated by Django 5.2.15 on 2026-06-23 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exploitations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Utilisateur'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('audio_url', models.TextField(blank=True)),
                ('extracted_action', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to='exploitations.exploitation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'conversation IA',
                'verbose_name_plural': 'conversations IA',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('summary', models.TextField(blank=True)),
                ('dti_score', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('kwh_per_m3', models.FloatField(blank=True, null=True)),
                ('water_used_m3', models.FloatField(blank=True, null=True)),
                ('energy_used_kwh', models.FloatField(blank=True, null=True)),
                ('alerts_count', models.IntegerField(default=0)),
                ('recommendations', models.JSONField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='exploitations.exploitation')),
            ],
            options={
                'verbose_name': 'rapport quotidien',
                'verbose_name_plural': 'rapports quotidiens',
                'ordering': ('-report_date',),
            },
        ),
        migrations.CreateModel(
            name='VocalDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255)),
                ('replacement', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('parcelle', 'Parcelle'), ('culture', 'Culture'), ('materiel', 'Matériel'), ('produit', 'Produit'), ('general', 'Général')], default='general', max_length=12)),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocal_dictionary', to='exploitations.exploitation')),
            ],
            options={
                'verbose_name': 'terme vocal',
                'verbose_name_plural': 'dictionnaire vocal',
            },
        ),
    ]
