# Generated by Django 5.2.15 on 2026-07-20 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exploitations', '0007_exploitation_alertes_gel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=255, verbose_name='intitulé')),
                ('type_contrat', models.CharField(choices=[('bail', 'Bail rural / fermage'), ('prestation', 'Prestation de service'), ('vente', 'Contrat de vente'), ('appro', 'Approvisionnement'), ('assurance', 'Assurance'), ('salarie', 'Contrat de travail'), ('autre', 'Autre')], default='autre', max_length=20, verbose_name='type')),
                ('contractant', models.CharField(blank=True, max_length=255, verbose_name='contractant')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='date de fin')),
                ('montant', models.FloatField(blank=True, null=True, verbose_name='montant (€)')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('actif', 'Actif'), ('expire', 'Expiré'), ('resilie', 'Résilié')], default='brouillon', max_length=12, verbose_name='statut')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='exploitations.exploitation')),
            ],
            options={
                'verbose_name': 'contrat',
                'verbose_name_plural': 'contrats',
                'ordering': ('-date_debut', '-created_at'),
                'indexes': [models.Index(fields=['exploitation', 'statut'], name='contrat_con_exploit_1fa4ef_idx')],
            },
        ),
    ]
