# Generated by Django 5.2.15 on 2026-07-20 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat', '0001_initial'),
        ('exploitations', '0007_exploitation_alertes_gel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActeNotarie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=255, verbose_name='objet')),
                ('type_acte', models.CharField(choices=[('vente', 'Vente'), ('achat', 'Achat'), ('donation', 'Donation'), ('succession', 'Succession'), ('servitude', 'Servitude'), ('hypotheque', 'Hypothèque'), ('autre', 'Autre')], default='autre', max_length=20, verbose_name="type d'acte")),
                ('notaire', models.CharField(blank=True, max_length=255, verbose_name='notaire / étude')),
                ('parties', models.CharField(blank=True, max_length=255, verbose_name='parties')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name="référence de l'acte")),
                ('date_signature', models.DateField(blank=True, null=True, verbose_name='date de signature')),
                ('montant', models.FloatField(blank=True, null=True, verbose_name='montant (€)')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actes_notaries', to='exploitations.exploitation')),
            ],
            options={
                'verbose_name': 'acte notarié',
                'verbose_name_plural': 'actes notariés',
                'ordering': ('-date_signature', '-created_at'),
                'indexes': [models.Index(fields=['exploitation', 'type_acte'], name='contrat_act_exploit_01635a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Bail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255, verbose_name='désignation')),
                ('bailleur', models.CharField(blank=True, max_length=255, verbose_name='bailleur')),
                ('preneur', models.CharField(blank=True, max_length=255, verbose_name='preneur')),
                ('surface_ha', models.FloatField(blank=True, null=True, verbose_name='surface (ha)')),
                ('loyer_annuel', models.FloatField(blank=True, null=True, verbose_name='fermage annuel (€)')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='date de fin')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('actif', 'Actif'), ('expire', 'Expiré'), ('resilie', 'Résilié')], default='brouillon', max_length=12, verbose_name='statut')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baux', to='exploitations.exploitation')),
            ],
            options={
                'verbose_name': 'bail',
                'verbose_name_plural': 'baux',
                'ordering': ('-date_debut', '-created_at'),
                'indexes': [models.Index(fields=['exploitation', 'statut'], name='contrat_bai_exploit_67a2a2_idx')],
            },
        ),
    ]
