# Generated by Django 5.2.15 on 2026-07-20 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat', '0002_actenotarie_bail'),
        ('exploitations', '0007_exploitation_alertes_gel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=255, verbose_name='intitulé')),
                ('type_assurance', models.CharField(choices=[('multirisque', 'Multirisque agricole'), ('recolte', 'Récolte / climatique'), ('rc', 'Responsabilité civile'), ('materiel', 'Matériel'), ('batiments', 'Bâtiments'), ('grele', 'Grêle'), ('betail', 'Mortalité du bétail'), ('autre', 'Autre')], default='multirisque', max_length=20, verbose_name='type')),
                ('assureur', models.CharField(blank=True, max_length=255, verbose_name='assureur')),
                ('numero_police', models.CharField(blank=True, max_length=100, verbose_name='n° de police')),
                ('prime_annuelle', models.FloatField(blank=True, null=True, verbose_name='prime annuelle (€)')),
                ('capital_assure', models.FloatField(blank=True, null=True, verbose_name='capital assuré (€)')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='échéance')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('active', 'Active'), ('expiree', 'Expirée'), ('resiliee', 'Résiliée')], default='brouillon', max_length=12, verbose_name='statut')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assurances', to='exploitations.exploitation')),
            ],
            options={
                'verbose_name': 'assurance',
                'verbose_name_plural': 'assurances',
                'ordering': ('-date_debut', '-created_at'),
                'indexes': [models.Index(fields=['exploitation', 'statut'], name='contrat_ass_exploit_c6224c_idx')],
            },
        ),
    ]
