# Generated by Django 5.2.15 on 2026-07-21 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat', '0003_assurance'),
        ('exploitations', '0008_remove_exploitation_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Msa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=255, verbose_name='intitulé')),
                ('type_cotisation', models.CharField(choices=[('amexa', 'AMEXA — maladie exploitant'), ('retraite', 'Retraite (AVI/AVA/RCO)'), ('atexa', 'ATEXA — accidents du travail'), ('allocations', 'Allocations familiales'), ('csg_crds', 'CSG / CRDS'), ('formation', 'Formation (VIVEA)'), ('salaries', 'Cotisations salariés'), ('autre', 'Autre')], default='amexa', max_length=15, verbose_name='type de cotisation')),
                ('numero_adherent', models.CharField(blank=True, max_length=50, verbose_name="n° d'adhérent MSA")),
                ('caisse', models.CharField(blank=True, max_length=255, verbose_name='caisse MSA')),
                ('montant', models.FloatField(blank=True, null=True, verbose_name='montant (€)')),
                ('periode', models.CharField(blank=True, max_length=50, verbose_name='période / année')),
                ('date_echeance', models.DateField(blank=True, null=True, verbose_name='échéance')),
                ('statut', models.CharField(choices=[('a_payer', 'À payer'), ('payee', 'Payée'), ('en_retard', 'En retard'), ('exoneree', 'Exonérée')], default='a_payer', max_length=12, verbose_name='statut')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotisations_msa', to='exploitations.exploitation')),
            ],
            options={
                'verbose_name': 'cotisation MSA',
                'verbose_name_plural': 'cotisations MSA',
                'ordering': ('-date_echeance', '-created_at'),
                'indexes': [models.Index(fields=['exploitation', 'statut'], name='contrat_msa_exploit_eb6547_idx')],
            },
        ),
    ]
