# Generated by Django 5.2.15 on 2026-07-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat', '0004_msa'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndiceFermage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField(unique=True, verbose_name='année')),
                ('variation_pct', models.DecimalField(decimal_places=2, help_text="Variation de l'indice par rapport à l'année précédente, ex. 1,62", max_digits=6, verbose_name='variation (%)')),
                ('reference', models.CharField(blank=True, help_text='ex. arrêté du 15 juillet 2025', max_length=255, verbose_name="référence de l'arrêté")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'indice des fermages',
                'verbose_name_plural': 'indices des fermages',
                'ordering': ('-annee',),
            },
        ),
        migrations.AddField(
            model_name='bail',
            name='annee_reference',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='année de référence du loyer de base'),
        ),
        migrations.AddField(
            model_name='bail',
            name='loyer_base_ha',
            field=models.FloatField(blank=True, null=True, verbose_name='loyer de base (€/ha)'),
        ),
        migrations.AddField(
            model_name='bail',
            name='loyer_maxi_ha',
            field=models.FloatField(blank=True, null=True, verbose_name='maximum préfectoral (€/ha)'),
        ),
        migrations.AddField(
            model_name='bail',
            name='loyer_mini_ha',
            field=models.FloatField(blank=True, null=True, verbose_name='minimum préfectoral (€/ha)'),
        ),
    ]
