# Generated by Django 5.2.15 on 2026-08-21 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_partenaire_user'),
        ('contrat', '0005_indicefermage_bail_annee_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bail',
            name='partenaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baux', to='client.partenaire', verbose_name='fiche bailleur'),
        ),
    ]
