# Generated by Django 5.2.15 on 2026-09-02 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat', '0006_bail_partenaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='assurance',
            name='courtier',
            field=models.CharField(blank=True, max_length=255, verbose_name='courtier ou agence'),
        ),
        migrations.AddField(
            model_name='assurance',
            name='date_resiliation',
            field=models.DateField(blank=True, null=True, verbose_name='résiliée le'),
        ),
        migrations.AddField(
            model_name='assurance',
            name='delai_declaration_jours',
            field=models.PositiveIntegerField(blank=True, help_text='Cinq jours ouvrés en général, deux pour le vol, dix après un arrêté de catastrophe naturelle.', null=True, verbose_name='délai de déclaration (jours)'),
        ),
        migrations.AddField(
            model_name='assurance',
            name='email_courtier',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email du courtier'),
        ),
        migrations.AddField(
            model_name='assurance',
            name='email_sinistre',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email sinistre'),
        ),
        migrations.AddField(
            model_name='assurance',
            name='exclusions',
            field=models.TextField(blank=True, verbose_name='exclusions'),
        ),
        migrations.AddField(
            model_name='assurance',
            name='franchise',
            field=models.CharField(blank=True, max_length=255, verbose_name='franchise'),
        ),
        migrations.AddField(
            model_name='assurance',
            name='garanties',
            field=models.TextField(blank=True, verbose_name='garanties'),
        ),
        migrations.AddField(
            model_name='assurance',
            name='plafond',
            field=models.FloatField(blank=True, null=True, verbose_name="plafond d'indemnisation (€)"),
        ),
        migrations.AddField(
            model_name='assurance',
            name='preavis_resiliation_jours',
            field=models.PositiveIntegerField(blank=True, help_text="Deux mois avant l'échéance dans la plupart des contrats.", null=True, verbose_name='préavis de résiliation (jours)'),
        ),
        migrations.AddField(
            model_name='assurance',
            name='procedure_sinistre',
            field=models.TextField(blank=True, verbose_name='marche à suivre en cas de sinistre'),
        ),
        migrations.AddField(
            model_name='assurance',
            name='tacite_reconduction',
            field=models.BooleanField(default=True, verbose_name='tacite reconduction'),
        ),
        migrations.AddField(
            model_name='assurance',
            name='telephone_courtier',
            field=models.CharField(blank=True, max_length=30, verbose_name='téléphone du courtier'),
        ),
        migrations.AddField(
            model_name='assurance',
            name='telephone_sinistre',
            field=models.CharField(blank=True, max_length=30, verbose_name='téléphone sinistre'),
        ),
        migrations.AlterField(
            model_name='assurance',
            name='type_assurance',
            field=models.CharField(choices=[('multirisque', 'Multirisque agricole'), ('recolte', 'Multirisque climatique (récoltes)'), ('grele', 'Grêle'), ('rc', 'Responsabilité civile exploitation'), ('rc_dirigeant', 'Responsabilité civile du dirigeant'), ('vehicules', 'Véhicules et engins'), ('materiel', 'Matériel et bris de machine'), ('batiments', 'Bâtiments'), ('betail', 'Cheptel et mortalité du bétail'), ('perte_exploitation', "Perte d'exploitation"), ('protection_juridique', 'Protection juridique'), ('environnement', "Atteinte à l'environnement"), ('sante_prevoyance', 'Santé et prévoyance'), ('emprunteur', 'Emprunteur'), ('construction', 'Construction / dommages-ouvrage'), ('transport', 'Transport de marchandises'), ('cyber', 'Cyber'), ('autre', 'Autre')], default='multirisque', max_length=20, verbose_name='type'),
        ),
        migrations.CreateModel(
            name='DocumentAssurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='assurances/%Y/%m/', verbose_name='fichier')),
                ('nom', models.CharField(blank=True, max_length=255, verbose_name='nom')),
                ('type_document', models.CharField(choices=[('police', 'Contrat / police'), ('conditions', 'Conditions générales'), ('avenant', 'Avenant'), ('attestation', 'Attestation'), ('appel_prime', 'Appel de prime'), ('sinistre', 'Déclaration de sinistre'), ('autre', 'Autre')], default='police', max_length=15, verbose_name='type')),
                ('extraction', models.JSONField(blank=True, default=dict, verbose_name='extraction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='contrat.assurance')),
            ],
            options={
                'verbose_name': "document d'assurance",
                'verbose_name_plural': "documents d'assurance",
                'ordering': ('-created_at',),
            },
        ),
    ]
