# Generated by Django 5.2.15 on 2026-09-02 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat', '0007_assurance_courtier_assurance_date_resiliation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bail',
            name='charges_recuperables',
            field=models.TextField(blank=True, verbose_name='charges récupérables'),
        ),
        migrations.AddField(
            model_name='bail',
            name='clauses_environnementales',
            field=models.TextField(blank=True, verbose_name='clauses environnementales'),
        ),
        migrations.AddField(
            model_name='bail',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email du bailleur'),
        ),
        migrations.AddField(
            model_name='bail',
            name='contact_telephone',
            field=models.CharField(blank=True, max_length=30, verbose_name='téléphone du bailleur'),
        ),
        migrations.AddField(
            model_name='bail',
            name='date_resiliation',
            field=models.DateField(blank=True, null=True, verbose_name='résilié le'),
        ),
        migrations.AddField(
            model_name='bail',
            name='date_revision_fermage',
            field=models.DateField(blank=True, help_text="Date anniversaire à laquelle l'indice s'applique.", null=True, verbose_name='date de révision du fermage'),
        ),
        migrations.AddField(
            model_name='bail',
            name='droit_preemption',
            field=models.TextField(blank=True, verbose_name='droit de préemption'),
        ),
        migrations.AddField(
            model_name='bail',
            name='etat_des_lieux',
            field=models.BooleanField(default=False, verbose_name='état des lieux établi'),
        ),
        migrations.AddField(
            model_name='bail',
            name='preavis_conge_mois',
            field=models.PositiveIntegerField(default=18, help_text='Dix-huit mois avant le terme pour un bail rural : au-delà, le bail se renouvelle de plein droit.', verbose_name='préavis de congé (mois)'),
        ),
        migrations.AddField(
            model_name='bail',
            name='references_cadastrales',
            field=models.TextField(blank=True, verbose_name='références cadastrales'),
        ),
        migrations.AddField(
            model_name='bail',
            name='renouvellement_tacite',
            field=models.BooleanField(default=True, verbose_name='renouvellement tacite'),
        ),
        migrations.AddField(
            model_name='bail',
            name='taxe_fonciere_part_preneur',
            field=models.FloatField(blank=True, null=True, verbose_name='part de taxe foncière au preneur (%)'),
        ),
        migrations.AddField(
            model_name='bail',
            name='type_bail',
            field=models.CharField(choices=[('ferme_9', 'Bail à ferme (9 ans)'), ('long_terme_18', 'Bail à long terme (18 ans)'), ('long_terme_25', 'Bail à long terme (25 ans et plus)'), ('carriere', 'Bail de carrière'), ('cessible', 'Bail cessible hors cadre familial'), ('paturage', 'Convention pluriannuelle de pâturage'), ('metayage', 'Bail à métayage'), ('commodat', 'Commodat (prêt à usage)'), ('safer', 'Mise à disposition SAFER'), ('precaire', 'Convention précaire'), ('autre', 'Autre')], default='ferme_9', max_length=15, verbose_name='type de bail'),
        ),
        migrations.CreateModel(
            name='DocumentBail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='baux/%Y/%m/', verbose_name='fichier')),
                ('nom', models.CharField(blank=True, max_length=255, verbose_name='nom')),
                ('type_document', models.CharField(choices=[('bail', 'Bail'), ('etat_des_lieux', 'État des lieux'), ('avenant', 'Avenant'), ('quittance', 'Quittance de fermage'), ('conge', 'Congé'), ('plan', 'Plan ou extrait cadastral'), ('autre', 'Autre')], default='bail', max_length=15, verbose_name='type')),
                ('extraction', models.JSONField(blank=True, default=dict, verbose_name='extraction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='contrat.bail')),
            ],
            options={
                'verbose_name': 'document de bail',
                'verbose_name_plural': 'documents de bail',
                'ordering': ('-created_at',),
            },
        ),
    ]
