# Generated by Django 5.2.15 on 2026-09-03 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat', '0008_bail_charges_recuperables_and_more'),
        ('exploitations', '0021_exploitation_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentActe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='actes/%Y/%m/', verbose_name='fichier')),
                ('nom', models.CharField(blank=True, max_length=255, verbose_name='nom')),
                ('type_document', models.CharField(choices=[('acte', 'Acte authentique'), ('promesse', 'Promesse ou compromis'), ('attestation', 'Attestation de propriété'), ('titre', 'Titre de propriété'), ('plan', 'Plan ou extrait cadastral'), ('etat_hypo', 'État hypothécaire'), ('mainlevee', 'Mainlevée'), ('quittance', 'Quittance'), ('procuration', 'Procuration'), ('autre', 'Autre')], default='acte', max_length=15, verbose_name='type')),
                ('extraction', models.JSONField(blank=True, default=dict, verbose_name='extraction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "document d'acte",
                'verbose_name_plural': "documents d'acte",
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='actenotarie',
            name='charges_et_servitudes',
            field=models.TextField(blank=True, verbose_name='charges et servitudes'),
        ),
        migrations.AddField(
            model_name='actenotarie',
            name='conditions_suspensives',
            field=models.TextField(blank=True, verbose_name='conditions suspensives'),
        ),
        migrations.AddField(
            model_name='actenotarie',
            name='date_limite_realisation',
            field=models.DateField(blank=True, help_text="Terme de la promesse : passé, l'avant-contrat est caduc.", null=True, verbose_name='date limite de réitération'),
        ),
        migrations.AddField(
            model_name='actenotarie',
            name='date_peremption',
            field=models.DateField(blank=True, help_text="Pour une hypothèque : date à laquelle l'inscription cesse d'avoir effet.", null=True, verbose_name="péremption de l'inscription"),
        ),
        migrations.AddField(
            model_name='actenotarie',
            name='date_promesse',
            field=models.DateField(blank=True, null=True, verbose_name='date de la promesse'),
        ),
        migrations.AddField(
            model_name='actenotarie',
            name='date_publication',
            field=models.DateField(blank=True, help_text="Tant qu'il n'est pas publié, l'acte reste inopposable aux tiers.", null=True, verbose_name='publication au fichier immobilier'),
        ),
        migrations.AddField(
            model_name='actenotarie',
            name='droit_preemption',
            field=models.TextField(blank=True, verbose_name='droit de préemption'),
        ),
        migrations.AddField(
            model_name='actenotarie',
            name='droits_enregistrement',
            field=models.FloatField(blank=True, null=True, verbose_name="droits d'enregistrement (€)"),
        ),
        migrations.AddField(
            model_name='actenotarie',
            name='email_notaire',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email du notaire'),
        ),
        migrations.AddField(
            model_name='actenotarie',
            name='frais_notaire',
            field=models.FloatField(blank=True, null=True, verbose_name='frais de notaire (€)'),
        ),
        migrations.AddField(
            model_name='actenotarie',
            name='mainlevee_obtenue',
            field=models.BooleanField(default=False, verbose_name='mainlevée obtenue'),
        ),
        migrations.AddField(
            model_name='actenotarie',
            name='references_cadastrales',
            field=models.TextField(blank=True, verbose_name='références cadastrales'),
        ),
        migrations.AddField(
            model_name='actenotarie',
            name='statut',
            field=models.CharField(choices=[('projet', 'Projet'), ('promesse', 'Promesse ou compromis signé'), ('signe', 'Signé'), ('publie', 'Publié au fichier immobilier'), ('caduc', 'Caduc')], default='projet', max_length=12, verbose_name='statut'),
        ),
        migrations.AddField(
            model_name='actenotarie',
            name='surface_ha',
            field=models.FloatField(blank=True, null=True, verbose_name='surface (ha)'),
        ),
        migrations.AddField(
            model_name='actenotarie',
            name='telephone_notaire',
            field=models.CharField(blank=True, max_length=30, verbose_name='téléphone du notaire'),
        ),
        migrations.AlterField(
            model_name='actenotarie',
            name='type_acte',
            field=models.CharField(choices=[('vente', 'Vente'), ('achat', 'Achat'), ('echange', 'Échange de parcelles'), ('donation', 'Donation'), ('donation_partage', 'Donation-partage'), ('succession', 'Succession'), ('partage', 'Partage'), ('testament', 'Testament'), ('demembrement', 'Démembrement (usufruit / nue-propriété)'), ('servitude', 'Servitude'), ('hypotheque', 'Hypothèque ou privilège de prêteur'), ('mainlevee', "Mainlevée d'hypothèque"), ('pret', 'Acte de prêt'), ('bail_emphyteotique', 'Bail emphytéotique'), ('societe', 'Constitution de société (GFA, GAEC, EARL)'), ('apport', 'Apport en société'), ('attestation', 'Attestation de propriété'), ('procuration', 'Procuration'), ('autre', 'Autre')], default='autre', max_length=20, verbose_name="type d'acte"),
        ),
        migrations.AddIndex(
            model_name='actenotarie',
            index=models.Index(fields=['exploitation', 'statut'], name='contrat_act_exploit_808107_idx'),
        ),
        migrations.AddField(
            model_name='documentacte',
            name='acte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='contrat.actenotarie'),
        ),
    ]
