# Generated by Django 5.2.15 on 2026-09-03 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat', '0009_documentacte_actenotarie_charges_et_servitudes_and_more'),
        ('exploitations', '0024_exploitation_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='nom')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to='exploitations.exploitation')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enfants', to='contrat.dossier', verbose_name='dossier parent')),
            ],
            options={
                'verbose_name': 'dossier',
                'verbose_name_plural': 'dossiers',
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='Fichier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='nom')),
                ('fichier', models.FileField(upload_to='drive/%Y/%m/', verbose_name='fichier')),
                ('taille', models.PositiveBigIntegerField(default=0, verbose_name='taille')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('depose_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='déposé par')),
                ('dossier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fichiers', to='contrat.dossier', verbose_name='dossier')),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers', to='exploitations.exploitation')),
            ],
            options={
                'verbose_name': 'fichier',
                'verbose_name_plural': 'fichiers',
                'ordering': ('nom',),
            },
        ),
        migrations.AddConstraint(
            model_name='dossier',
            constraint=models.UniqueConstraint(fields=('exploitation', 'parent', 'nom'), name='dossier_unique_dans_son_parent'),
        ),
        migrations.AddConstraint(
            model_name='dossier',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('exploitation', 'nom'), name='dossier_unique_a_la_racine'),
        ),
        migrations.AddIndex(
            model_name='fichier',
            index=models.Index(fields=['exploitation', 'dossier'], name='contrat_fic_exploit_1e8a5d_idx'),
        ),
    ]
