# Generated by Django 5.2.15 on 2026-06-23 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exploitations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='nom')),
                ('area', models.FloatField(blank=True, null=True, verbose_name='surface (ha)')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('boundaries', models.JSONField(blank=True, null=True, verbose_name='polygone')),
                ('agro_polygon_id', models.CharField(blank=True, max_length=100)),
                ('irrigation_type', models.CharField(blank=True, choices=[('goutte_a_goutte', 'Goutte à goutte'), ('aspersion', 'Aspersion'), ('enrouleur', 'Enrouleur'), ('pivot', 'Pivot'), ('micro_aspersion', 'Micro-aspersion'), ('gravitaire', 'Gravitaire')], max_length=20, verbose_name="type d'irrigation")),
                ('theoretical_flow_m3h', models.FloatField(blank=True, null=True, verbose_name='débit théorique (m³/h)')),
                ('nozzle_count', models.IntegerField(blank=True, null=True, verbose_name='nombre de buses')),
                ('nozzle_flow_lh', models.FloatField(blank=True, null=True, verbose_name='débit buse (L/h)')),
                ('row_spacing_m', models.FloatField(blank=True, null=True, verbose_name='écart entre rangs (m)')),
                ('emitter_spacing_m', models.FloatField(blank=True, null=True, verbose_name='écart entre émetteurs (m)')),
                ('service_pressure_bar', models.FloatField(blank=True, null=True, verbose_name='pression de service (bar)')),
                ('culture', models.CharField(blank=True, max_length=100, verbose_name='culture')),
                ('variety', models.CharField(blank=True, max_length=100, verbose_name='variété')),
                ('kc_value', models.FloatField(default=1.0, verbose_name='coefficient Kc')),
                ('tree_age_years', models.IntegerField(blank=True, null=True, verbose_name='âge des plants (ans)')),
                ('planting_date', models.DateField(blank=True, null=True, verbose_name='date de plantation')),
                ('plant_density_per_ha', models.IntegerField(blank=True, null=True, verbose_name='densité (pieds/ha)')),
                ('soil_type', models.CharField(blank=True, max_length=100, verbose_name='type de sol')),
                ('root_depth', models.FloatField(blank=True, null=True, verbose_name='profondeur racinaire')),
                ('root_depth_cm', models.IntegerField(blank=True, null=True, verbose_name='profondeur racinaire (cm)')),
                ('soil_retention_mm_m', models.FloatField(blank=True, null=True, verbose_name='rétention sol (mm/m)')),
                ('soil_ph', models.FloatField(blank=True, null=True, verbose_name='pH du sol')),
                ('cadastral_ref', models.CharField(blank=True, max_length=50, verbose_name='réf. cadastrale')),
                ('commune', models.CharField(blank=True, max_length=100, verbose_name='commune')),
                ('official_area_ha', models.FloatField(blank=True, null=True, verbose_name='surface officielle (ha)')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('jachere', 'Jachère')], default='active', max_length=10)),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelles', to='exploitations.exploitation')),
            ],
            options={
                'verbose_name': 'parcelle',
                'verbose_name_plural': 'parcelles',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CropStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage_name', models.CharField(max_length=100, verbose_name='stade')),
                ('stage_code', models.CharField(blank=True, max_length=20)),
                ('start_date', models.DateField(verbose_name='début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='fin')),
                ('kc_value', models.FloatField(verbose_name='coefficient Kc')),
                ('root_depth_m', models.FloatField(blank=True, null=True, verbose_name='profondeur racinaire (m)')),
                ('notes', models.TextField(blank=True)),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_stages', to='parcelles.parcelle')),
            ],
            options={
                'verbose_name': 'stade cultural',
                'verbose_name_plural': 'stades culturaux',
                'ordering': ('start_date',),
            },
        ),
        migrations.AddIndex(
            model_name='parcelle',
            index=models.Index(fields=['exploitation', 'status'], name='parcelles_p_exploit_fe3907_idx'),
        ),
    ]
