# Generated by Django 5.2.15 on 2026-06-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelle',
            name='acquired_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="date d'acquisition"),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='cadastre_data',
            field=models.JSONField(blank=True, null=True, verbose_name='données cadastre (brut IGN)'),
        ),
    ]
