# Generated by Django 5.2.15 on 2026-07-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelles', '0002_parcelle_acquired_at_parcelle_cadastre_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelle',
            name='surface_utile',
            field=models.BooleanField(default=True, help_text="Cette surface compte-t-elle dans la SAU de l'exploitation ?", verbose_name='surface agricole utile (SAU)'),
        ),
    ]
