# Generated by Django 5.2.15 on 2026-07-24 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelles', '0004_parcelle_type_agriculture'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelleCampagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('libelle', models.CharField(help_text='Libellé année-année, ex. « 2025/2026 ».', max_length=20, verbose_name='campagne')),
                ('culture', models.CharField(blank=True, max_length=100, verbose_name='culture')),
                ('variety', models.CharField(blank=True, max_length=100, verbose_name='variété')),
                ('kc_value', models.FloatField(default=1.0, verbose_name='coefficient Kc')),
                ('tree_age_years', models.IntegerField(blank=True, null=True, verbose_name='âge des plants (ans)')),
                ('planting_date', models.DateField(blank=True, null=True, verbose_name='date de plantation')),
                ('plant_density_per_ha', models.IntegerField(blank=True, null=True, verbose_name='densité (pieds/ha)')),
                ('irrigation_type', models.CharField(blank=True, choices=[('goutte_a_goutte', 'Goutte à goutte'), ('aspersion', 'Aspersion'), ('enrouleur', 'Enrouleur'), ('pivot', 'Pivot'), ('micro_aspersion', 'Micro-aspersion'), ('gravitaire', 'Gravitaire')], max_length=20, verbose_name="type d'irrigation")),
                ('theoretical_flow_m3h', models.FloatField(blank=True, null=True, verbose_name='débit théorique (m³/h)')),
                ('nozzle_count', models.IntegerField(blank=True, null=True, verbose_name='nombre de buses')),
                ('nozzle_flow_lh', models.FloatField(blank=True, null=True, verbose_name='débit buse (L/h)')),
                ('row_spacing_m', models.FloatField(blank=True, null=True, verbose_name='écart entre rangs (m)')),
                ('emitter_spacing_m', models.FloatField(blank=True, null=True, verbose_name='écart entre émetteurs (m)')),
                ('service_pressure_bar', models.FloatField(blank=True, null=True, verbose_name='pression de service (bar)')),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campagnes', to='parcelles.parcelle')),
            ],
            options={
                'verbose_name': 'campagne de parcelle',
                'verbose_name_plural': 'campagnes de parcelle',
                'ordering': ('-libelle',),
            },
        ),
        migrations.AddField(
            model_name='cropstage',
            name='parcelle_campagne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crop_stages', to='parcelles.parcellecampagne'),
        ),
        migrations.AddConstraint(
            model_name='parcellecampagne',
            constraint=models.UniqueConstraint(fields=('parcelle', 'libelle'), name='unique_parcelle_campagne'),
        ),
    ]
