# Generated by Django 5.2.15 on 2026-07-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelles', '0007_remove_culture_irrigation_from_parcelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcellecampagne',
            name='type_culture',
            field=models.CharField(blank=True, help_text='Déduit de la culture choisie si laissé vide.', max_length=20, verbose_name='type de culture'),
        ),
    ]
