# Generated by Django 5.2.15 on 2026-07-27 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelles', '0008_parcellecampagne_type_culture'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelle',
            name='orientation_rangs_deg',
            field=models.PositiveSmallIntegerField(blank=True, help_text='0–359° (0 = Nord) — se règle sur la carte des parcelles.', null=True, verbose_name='sens des rangs (° / Nord)'),
        ),
    ]
