# Generated by Django 5.2.15 on 2026-06-23 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exploitations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sondage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=255, verbose_name='question')),
                ('closed', models.BooleanField(default=False, verbose_name='clôturé')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('exploitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sondages', to='exploitations.exploitation')),
            ],
            options={
                'verbose_name': 'sondage',
                'verbose_name_plural': 'sondages',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Choix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=255, verbose_name='texte')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('sondage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choix', to='sondages.sondage')),
            ],
            options={
                'verbose_name': 'choix',
                'verbose_name_plural': 'choix',
                'ordering': ('ordre', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('choix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='sondages.choix')),
                ('sondage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='sondages.sondage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'vote',
                'verbose_name_plural': 'votes',
                'unique_together': {('sondage', 'user')},
            },
        ),
    ]
