# Generated by Django 5.2.15 on 2026-06-24 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Intervention',
        ),
    ]
