# Generated by Django 5.2.15 on 2026-09-02 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_alter_partenaire_type_partenaire'),
        ('exploitations', '0021_exploitation_logo'),
        ('operations', '0004_types_materiel'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='detention',
            field=models.CharField(choices=[('propre', 'En propre'), ('cuma', 'En CUMA'), ('copropriete', 'En copropriété'), ('location', 'En location'), ('eta', 'Confié à une ETA')], default='propre', max_length=15, verbose_name='détention'),
        ),
        migrations.AddField(
            model_name='machine',
            name='proprietaire',
            field=models.ForeignKey(blank=True, help_text="La CUMA, le loueur ou l'ETA à qui appartient l'engin. Vide quand il est à l'exploitation.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiels', to='client.partenaire', verbose_name='propriétaire'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['exploitation', 'detention'], name='operations__exploit_8a583a_idx'),
        ),
    ]
