# Generated by Django 5.2.15 on 2026-09-02 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exploitations', '0021_exploitation_logo'),
        ('operations', '0005_machine_detention_machine_proprietaire_and_more'),
        ('parcelles', '0009_parcelle_orientation_rangs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectationengin',
            name='parcelle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parcelles.parcelle', verbose_name='parcelle'),
        ),
        migrations.AddIndex(
            model_name='affectationengin',
            index=models.Index(fields=['exploitation', 'date_debut'], name='operations__exploit_85677a_idx'),
        ),
    ]
