# Generated by Django 5.2.15 on 2026-07-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0003_program_parcelles_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='ndvidata',
            name='ndwi_max',
            field=models.FloatField(blank=True, null=True, verbose_name='NDWI max'),
        ),
        migrations.AddField(
            model_name='ndvidata',
            name='ndwi_mean',
            field=models.FloatField(blank=True, null=True, verbose_name='NDWI moyen'),
        ),
        migrations.AddField(
            model_name='ndvidata',
            name='ndwi_min',
            field=models.FloatField(blank=True, null=True, verbose_name='NDWI min'),
        ),
    ]
