# Generated by Django 5.2.15 on 2026-07-25 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exploitations', '0010_exploitation_meteo_masquer_lieu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bassin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='nom')),
                ('type_bassin', models.CharField(choices=[('etang', 'Étang'), ('bassin', 'Bassin'), ('raceway', 'Raceway / canal'), ('cage', 'Cage flottante'), ('ras', 'Circuit fermé (RAS)'), ('marais', 'Marais'), ('table', 'Table ostréicole'), ('filiere', 'Filière / corde'), ('autre', 'Autre')], default='bassin', max_length=15, verbose_name="type d'installation")),
                ('statut', models.CharField(choices=[('en_service', 'En service'), ('assec', 'En assec'), ('maintenance', 'En maintenance'), ('hors_service', 'Hors service')], default='en_service', max_length=15, verbose_name='statut')),
                ('source_eau', models.CharField(blank=True, choices=[('forage', 'Forage'), ('riviere', 'Rivière'), ('source', 'Source'), ('mer', 'Mer'), ('reseau', 'Réseau'), ('pluvial', 'Pluvial'), ('autre', 'Autre')], max_length=15, verbose_name="source d'eau")),
                ('surface_m2', models.FloatField(blank=True, null=True, verbose_name='surface (m²)')),
                ('volume_m3', models.FloatField(blank=True, null=True, verbose_name='volume (m³)')),
                ('profondeur_m', models.FloatField(blank=True, null=True, verbose_name='profondeur moyenne (m)')),
                ('temperature_cible_c', models.FloatField(blank=True, null=True, verbose_name='température cible (°C)')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bassins', to='exploitations.exploitation')),
            ],
            options={
                'verbose_name': 'installation aquacole',
                'verbose_name_plural': 'installations aquacoles',
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espece', models.CharField(max_length=255, verbose_name='espèce')),
                ('souche', models.CharField(blank=True, max_length=255, verbose_name='souche / origine')),
                ('effectif', models.PositiveIntegerField(blank=True, null=True, verbose_name='effectif')),
                ('poids_moyen_g', models.FloatField(blank=True, null=True, verbose_name='poids moyen (g)')),
                ('date_mise_en_charge', models.DateField(blank=True, null=True, verbose_name='mise en charge')),
                ('statut', models.CharField(choices=[('en_elevage', 'En élevage'), ('recolte', 'Récolté'), ('perdu', 'Perte')], default='en_elevage', max_length=12, verbose_name='statut')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bassin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='aquaculture.bassin')),
            ],
            options={
                'verbose_name': 'lot aquacole',
                'verbose_name_plural': 'lots aquacoles',
                'ordering': ('-date_mise_en_charge', 'espece'),
            },
        ),
        migrations.AddIndex(
            model_name='bassin',
            index=models.Index(fields=['exploitation', 'statut'], name='aquaculture_exploit_813477_idx'),
        ),
        migrations.AddIndex(
            model_name='lot',
            index=models.Index(fields=['bassin', 'statut'], name='aquaculture_bassin__17dcd6_idx'),
        ),
    ]
