# Generated by Django 5.2.15 on 2026-07-25 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaculture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspeceAquacole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=255, verbose_name='nom')),
                ('nom_scientifique', models.CharField(blank=True, max_length=255, verbose_name='nom scientifique')),
                ('famille', models.CharField(choices=[('poisson_eau_douce', "Poissons d'eau douce"), ('poisson_marin', 'Poissons marins'), ('diadrome', 'Poissons migrateurs'), ('coquillages', 'Coquillages'), ('crustaces', 'Crustacés'), ('algues', 'Algues'), ('autre', 'Autre')], default='autre', max_length=20, verbose_name='famille')),
                ('milieu', models.CharField(choices=[('douce', 'Eau douce'), ('saumatre', 'Eau saumâtre'), ('marine', 'Eau de mer')], default='douce', max_length=10, verbose_name='milieu')),
                ('production', models.CharField(choices=[('chair', 'Chair'), ('caviar', 'Œufs / caviar'), ('naissain', 'Naissain'), ('alevins', 'Alevins'), ('repeuplement', 'Repeuplement'), ('ornement', 'Ornement'), ('algues', 'Algues'), ('autre', 'Autre')], default='chair', max_length=15, verbose_name='production')),
                ('duree_cycle_jours', models.PositiveIntegerField(blank=True, null=True, verbose_name="durée du cycle d'élevage (jours)")),
                ('temperature_optimale_c', models.FloatField(blank=True, null=True, verbose_name='température optimale (°C)')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
            ],
            options={
                'verbose_name': 'espèce aquacole',
                'verbose_name_plural': 'espèces aquacoles',
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='Souche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=255, verbose_name='souche')),
                ('nom_scientifique', models.CharField(blank=True, max_length=255, verbose_name='nom scientifique')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='aquaculture/', verbose_name='photo')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('note', models.FloatField(blank=True, null=True, verbose_name='note (/5)')),
                ('nb_avis', models.PositiveIntegerField(default=0, verbose_name="nombre d'avis")),
                ('livree', models.CharField(blank=True, max_length=255, verbose_name='livrée / couleur')),
                ('poids_adulte', models.CharField(blank=True, max_length=100, verbose_name='poids adulte')),
                ('taille', models.CharField(blank=True, max_length=100, verbose_name='taille')),
                ('aptitude', models.CharField(blank=True, max_length=255, verbose_name='aptitude')),
                ('croissance', models.CharField(blank=True, max_length=100, verbose_name='croissance')),
                ('rusticite', models.CharField(blank=True, max_length=100, verbose_name='rusticité')),
                ('alimentation', models.CharField(blank=True, max_length=255, verbose_name='alimentation')),
                ('particularites', models.CharField(blank=True, max_length=255, verbose_name='particularités')),
                ('conseil_elevage', models.TextField(blank=True, verbose_name="conseil d'élevage")),
                ('origine', models.CharField(blank=True, max_length=255, verbose_name='origine')),
                ('origine_texte', models.TextField(blank=True, verbose_name='origine (historique)')),
                ('espece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='souches', to='aquaculture.especeaquacole')),
            ],
            options={
                'verbose_name': 'souche',
                'verbose_name_plural': 'souches',
                'ordering': ('nom',),
                'indexes': [models.Index(fields=['espece'], name='aquaculture_espece__597a67_idx')],
            },
        ),
    ]
