# Generated by Django 5.2.15 on 2026-09-03 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exploitations', '0024_exploitation_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_piece', models.CharField(choices=[('carte', "Carte d'identité"), ('passeport', 'Passeport'), ('signature', 'Signature')], max_length=12, verbose_name='type')),
                ('titulaire', models.CharField(blank=True, help_text="À qui appartient la pièce, si ce n'est pas vous.", max_length=160, verbose_name='titulaire')),
                ('numero', models.CharField(blank=True, max_length=60, verbose_name='numéro')),
                ('delivre_le', models.DateField(blank=True, null=True, verbose_name='délivrée le')),
                ('expire_le', models.DateField(blank=True, null=True, verbose_name='expire le')),
                ('fichier', models.FileField(upload_to='identite/%Y/%m/', verbose_name='fichier')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_identite', to='exploitations.exploitation')),
            ],
            options={
                'verbose_name': "pièce d'identité",
                'verbose_name_plural': "pièces d'identité",
                'ordering': ('type_piece', '-created_at'),
                'indexes': [models.Index(fields=['exploitation', 'type_piece'], name='identite_pi_exploit_dce77d_idx')],
            },
        ),
    ]
