# Generated by Django 5.2.15 on 2026-09-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='autorite',
            field=models.CharField(blank=True, help_text='Préfecture, sous-préfecture, mairie ou consulat.', max_length=160, verbose_name='autorité de délivrance'),
        ),
        migrations.AddField(
            model_name='piece',
            name='nom_usage',
            field=models.CharField(blank=True, help_text="S'il diffère du nom de famille : c'est souvent lui qui figure sur les contrats.", max_length=160, verbose_name="nom d'usage"),
        ),
        migrations.AddField(
            model_name='piece',
            name='prolongee',
            field=models.BooleanField(default=False, help_text="Carte délivrée à un majeur entre 2004 et 2013 : valable cinq ans de plus en France, mais refusée par certains pays à l'étranger.", verbose_name='validité prolongée de 5 ans'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='expire_le',
            field=models.DateField(blank=True, help_text='La date imprimée sur la pièce.', null=True, verbose_name='expire le'),
        ),
    ]
