# Generated by Django 5.2.15 on 2026-09-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identite', '0002_piece_autorite_piece_nom_usage_piece_prolongee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='par_defaut',
            field=models.BooleanField(default=False, verbose_name='signature active'),
        ),
    ]
