# Generated by Django 5.2.15 on 2026-06-23 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agronomie', '0002_fertigation'),
        ('exploitations', '0001_initial'),
        ('parcelles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('categorie', models.CharField(choices=[('semences', 'Semences'), ('engrais', 'Engrais'), ('phytosanitaires', 'Phytosanitaires'), ('eau', 'Eau'), ('energie', 'Énergie'), ('main_oeuvre', "Main d'œuvre"), ('materiel', 'Matériel'), ('transport', 'Transport'), ('assurance', 'Assurance'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('montant', models.FloatField()),
                ('description', models.CharField(blank=True, max_length=500)),
                ('fournisseur', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='exploitations.exploitation')),
                ('parcelle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parcelles.parcelle')),
            ],
            options={
                'verbose_name': 'charge',
                'verbose_name_plural': 'charges',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='FactureClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('adresse', models.TextField(blank=True)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('code_postal', models.CharField(blank=True, max_length=10)),
                ('siret', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facture_clients', to='exploitations.exploitation')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='Recolte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('quantite_kg', models.FloatField()),
                ('qualite', models.CharField(choices=[('extra', 'Extra'), ('cat1', 'Catégorie 1'), ('cat2', 'Catégorie 2'), ('declasse', 'Déclassé')], default='cat1', max_length=10)),
                ('prix_unitaire', models.FloatField(default=0)),
                ('cout_main_oeuvre', models.FloatField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoltes', to='exploitations.exploitation')),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoltes', to='parcelles.parcelle')),
            ],
            options={
                'verbose_name': 'récolte',
                'verbose_name_plural': 'récoltes',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Revenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('categorie', models.CharField(choices=[('vente_cereales', 'Vente céréales'), ('vente_fruits', 'Vente fruits'), ('vente_legumes', 'Vente légumes'), ('aide_pac', 'Aide PAC'), ('subvention', 'Subvention'), ('location', 'Location'), ('prestation', 'Prestation'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('montant', models.FloatField()),
                ('description', models.CharField(blank=True, max_length=500)),
                ('acheteur', models.CharField(blank=True, max_length=255)),
                ('quantite_kg', models.FloatField(blank=True, null=True)),
                ('prix_unitaire', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenus', to='exploitations.exploitation')),
                ('parcelle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parcelles.parcelle')),
                ('saison', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agronomie.saison')),
            ],
            options={
                'verbose_name': 'revenu',
                'verbose_name_plural': 'revenus',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='SubventionExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_type', models.CharField(choices=[('taxonomie_verte', 'Taxonomie Verte EU'), ('plan_eau_2026', 'Plan Eau 2026'), ('pac', 'PAC / France AgriMer'), ('feader', 'FEADER')], max_length=20)),
                ('file_url', models.TextField(blank=True)),
                ('file_key', models.TextField(blank=True)),
                ('period', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('generating', 'En génération'), ('ready', 'Prêt'), ('error', 'Erreur')], default='generating', max_length=12)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subvention_exports', to='exploitations.exploitation')),
            ],
            options={
                'verbose_name': 'export subvention',
                'verbose_name_plural': 'exports subvention',
                'ordering': ('-generated_at',),
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(max_length=30)),
                ('client_nom', models.CharField(blank=True, max_length=255)),
                ('date_emission', models.DateTimeField()),
                ('date_echeance', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente', 'En attente'), ('payee', 'Payée'), ('en_retard', 'En retard'), ('annulee', 'Annulée')], default='en_attente', max_length=12)),
                ('lignes', models.JSONField(blank=True, default=list)),
                ('montant_ht', models.FloatField(default=0)),
                ('taux_tva', models.FloatField(default=20)),
                ('montant_tva', models.FloatField(default=0)),
                ('montant_ttc', models.FloatField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='exploitations.exploitation')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='finances.factureclient')),
            ],
            options={
                'verbose_name': 'facture',
                'verbose_name_plural': 'factures',
                'ordering': ('-date_emission',),
                'constraints': [models.UniqueConstraint(fields=('exploitation', 'numero'), name='unique_facture_numero')],
            },
        ),
    ]
