# Generated by Django 5.2.15 on 2026-07-25 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revenu',
            name='saison',
        ),
    ]
