# Generated by Django 5.2.15 on 2026-08-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_remove_revenu_saison'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='superpdp_envoye_le',
            field=models.DateTimeField(blank=True, null=True, verbose_name='envoyée le'),
        ),
        migrations.AddField(
            model_name='facture',
            name='superpdp_erreur',
            field=models.TextField(blank=True, verbose_name='erreur SUPER PDP'),
        ),
        migrations.AddField(
            model_name='facture',
            name='superpdp_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='identifiant SUPER PDP'),
        ),
        migrations.AddField(
            model_name='facture',
            name='superpdp_statut',
            field=models.CharField(blank=True, max_length=20, verbose_name='statut SUPER PDP'),
        ),
        migrations.AddField(
            model_name='factureclient',
            name='superpdp_adresse',
            field=models.CharField(blank=True, help_text="Identifiant d'annuaire, par exemple « 0225:315143296_68152 ».", max_length=100, verbose_name='adresse de facturation électronique'),
        ),
    ]
