# Generated by Django 5.2.15 on 2026-08-24 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exploitations', '0021_exploitation_logo'),
        ('finances', '0003_facture_superpdp_envoye_le_facture_superpdp_erreur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(max_length=30)),
                ('client_nom', models.CharField(blank=True, max_length=255)),
                ('date_emission', models.DateTimeField()),
                ('date_validite', models.DateTimeField(blank=True, null=True, verbose_name="valable jusqu'au")),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoye', 'Envoyé'), ('accepte', 'Accepté'), ('refuse', 'Refusé'), ('expire', 'Expiré')], default='brouillon', max_length=12)),
                ('lignes', models.JSONField(blank=True, default=list)),
                ('montant_ht', models.FloatField(default=0)),
                ('taux_tva', models.FloatField(default=20)),
                ('montant_tva', models.FloatField(default=0)),
                ('montant_ttc', models.FloatField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis', to='finances.factureclient')),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devis', to='exploitations.exploitation')),
            ],
            options={
                'verbose_name': 'devis',
                'verbose_name_plural': 'devis',
                'ordering': ('-date_emission',),
            },
        ),
        migrations.AddField(
            model_name='facture',
            name='devis',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facture', to='finances.devis', verbose_name="devis d'origine"),
        ),
        migrations.AddConstraint(
            model_name='devis',
            constraint=models.UniqueConstraint(fields=('exploitation', 'numero'), name='unique_devis_numero'),
        ),
    ]
