# Generated by Django 5.2.15 on 2026-08-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_devis_facture_devis_devis_unique_devis_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='date_validite',
            field=models.DateTimeField(blank=True, null=True, verbose_name='valable jusqu’au'),
        ),
    ]
