# Generated by Django 5.2.15 on 2026-08-24 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_client_superpdp_adresse'),
        ('finances', '0005_alter_devis_date_validite'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='client_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis', to='client.client'),
        ),
        migrations.AddField(
            model_name='facture',
            name='client_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='client.client'),
        ),
    ]
