# Generated by Django 5.2.15 on 2026-08-24 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0007_reprise_clients_facturation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devis',
            name='client',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='client',
        ),
    ]
