# Generated by Django 5.2.15 on 2026-08-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0008_remove_devis_client_remove_facture_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='signature_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='signé le'),
        ),
        migrations.AddField(
            model_name='devis',
            name='signature_mention',
            field=models.CharField(blank=True, max_length=100, verbose_name='mention'),
        ),
        migrations.AddField(
            model_name='devis',
            name='signature_nom',
            field=models.CharField(blank=True, max_length=255, verbose_name='nom du signataire'),
        ),
        migrations.AddField(
            model_name='devis',
            name='signature_url',
            field=models.TextField(blank=True, verbose_name='signature'),
        ),
    ]
