# Generated by Django 5.2.15 on 2026-09-03 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exploitations', '0024_exploitation_photo'),
        ('finances', '0009_devis_signature_date_devis_signature_mention_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=120, verbose_name='nom')),
                ('fichier', models.ImageField(upload_to='logos/%Y/%m/', verbose_name='image')),
                ('par_defaut', models.BooleanField(default=False, help_text='Celui que prend un nouveau document, sauf choix contraire.', verbose_name='logo par défaut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logos', to='exploitations.exploitation')),
            ],
            options={
                'verbose_name': 'logo',
                'verbose_name_plural': 'logos',
                'ordering': ('-par_defaut', 'nom', '-created_at'),
            },
        ),
        migrations.AddField(
            model_name='devis',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='finances.logo', verbose_name='logo'),
        ),
        migrations.AddField(
            model_name='facture',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='finances.logo', verbose_name='logo'),
        ),
        migrations.AddIndex(
            model_name='logo',
            index=models.Index(fields=['exploitation', 'par_defaut'], name='finances_lo_exploit_8055ea_idx'),
        ),
    ]
