# Generated by Django 5.2.15 on 2026-09-03 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exploitations', '0024_exploitation_photo'),
        ('finances', '0010_logo_devis_logo_facture_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentiteFacturation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banque', models.CharField(blank=True, max_length=120, verbose_name='banque')),
                ('iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN')),
                ('bic', models.CharField(blank=True, max_length=11, verbose_name='BIC')),
                ('conditions_reglement', models.CharField(blank=True, help_text='ex : 30 jours fin de mois.', max_length=160, verbose_name='conditions de règlement')),
                ('capital_social', models.FloatField(blank=True, null=True, verbose_name='capital social (€)')),
                ('rcs', models.CharField(blank=True, help_text='ex : RCS Digne-les-Bains 123 456 789.', max_length=120, verbose_name='RCS / RM')),
                ('mentions', models.TextField(blank=True, help_text='Pénalités de retard, indemnité forfaitaire de recouvrement…', verbose_name='mentions de pied de page')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exploitation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identite_facturation', to='exploitations.exploitation')),
            ],
            options={
                'verbose_name': 'identité de facturation',
                'verbose_name_plural': 'identités de facturation',
            },
        ),
    ]
