# Generated by Django 5.2.15 on 2026-08-25 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exploitations', '0021_exploitation_logo'),
        ('stock', '0002_mouvement_recolte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='adresse de la boutique')),
                ('titre', models.CharField(blank=True, max_length=255, verbose_name='nom public')),
                ('accroche', models.CharField(blank=True, max_length=255, verbose_name='accroche')),
                ('description', models.TextField(blank=True, verbose_name='présentation')),
                ('est_ouverte', models.BooleanField(default=False, verbose_name='boutique ouverte')),
                ('visible_marche', models.BooleanField(default=True, verbose_name='visible sur la place de marché')),
                ('retrait_ferme', models.BooleanField(default=True, verbose_name='retrait à la ferme')),
                ('adresse_retrait', models.CharField(blank=True, max_length=255, verbose_name='lieu de retrait')),
                ('horaires_retrait', models.CharField(blank=True, max_length=255, verbose_name='horaires de retrait')),
                ('livraison', models.BooleanField(default=False, verbose_name='livraison')),
                ('rayon_livraison_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='rayon de livraison (km)')),
                ('zone_livraison', models.CharField(blank=True, max_length=255, verbose_name='zone livrée')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='téléphone public')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email public')),
                ('exploitation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boutique', to='exploitations.exploitation')),
            ],
            options={
                'verbose_name': 'boutique',
                'verbose_name_plural': 'boutiques',
                'ordering': ('titre',),
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=255, verbose_name='nom')),
                ('slug', models.SlugField(max_length=160, verbose_name='adresse')),
                ('categorie', models.CharField(choices=[('legume', 'Légumes'), ('fruit', 'Fruits'), ('viande', 'Viande'), ('volaille', 'Volaille'), ('oeuf', 'Œufs'), ('laitier', 'Produits laitiers'), ('fromage', 'Fromages'), ('cereale', 'Céréales et légumes secs'), ('farine', 'Farines'), ('huile', 'Huiles'), ('miel', 'Miel'), ('vin', 'Vins et spiritueux'), ('boisson', 'Jus et boissons'), ('epicerie', 'Épicerie et conserves'), ('plant', 'Plants et semences'), ('fleur', 'Fleurs'), ('fourrage', 'Fourrage et paille'), ('autre', 'Autre')], default='autre', max_length=12, verbose_name='catégorie')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='vente/produits/', verbose_name='photo')),
                ('unite_vente', models.CharField(choices=[('kg', 'au kilo'), ('piece', 'à la pièce'), ('colis', 'le colis'), ('panier', 'le panier'), ('barquette', 'la barquette'), ('botte', 'la botte'), ('litre', 'le litre'), ('bouteille', 'la bouteille'), ('pot', 'le pot'), ('douzaine', 'la douzaine'), ('sac', 'le sac')], default='kg', max_length=12, verbose_name='vendu')),
                ('conditionnement', models.FloatField(default=1, help_text='Quantité prélevée sur le stock pour une unité vendue (ex. 5 pour un colis de 5 kg).', verbose_name='contenu')),
                ('prix_ttc', models.FloatField(default=0, verbose_name='prix TTC (€)')),
                ('taux_tva', models.FloatField(default=5.5, verbose_name='TVA (%)')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_ligne', 'En ligne'), ('retire', 'Retiré')], default='brouillon', max_length=10, verbose_name='statut')),
                ('visible_marche', models.BooleanField(default=True, verbose_name='proposer sur la place de marché')),
                ('quantite_min', models.FloatField(default=1, verbose_name='commande minimum')),
                ('disponible_du', models.DateField(blank=True, null=True, verbose_name='disponible à partir du')),
                ('disponible_au', models.DateField(blank=True, null=True, verbose_name="disponible jusqu'au")),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='stock.article', verbose_name='article de stock')),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='exploitations.exploitation')),
            ],
            options={
                'verbose_name': 'produit',
                'verbose_name_plural': 'produits',
                'ordering': ('categorie', 'nom'),
                'indexes': [models.Index(fields=['exploitation', 'statut'], name='vente_produ_exploit_bb60d3_idx')],
                'constraints': [models.UniqueConstraint(fields=('exploitation', 'slug'), name='unique_produit_slug')],
            },
        ),
    ]
