# Generated by Django 5.2.15 on 2026-08-25 21:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_client_user'),
        ('exploitations', '0021_exploitation_logo'),
        ('stock', '0002_mouvement_recolte'),
        ('vente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(max_length=30, verbose_name='numéro')),
                ('jeton', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='jeton de suivi')),
                ('acheteur_nom', models.CharField(max_length=255, verbose_name='nom')),
                ('acheteur_email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('acheteur_telephone', models.CharField(blank=True, max_length=30, verbose_name='téléphone')),
                ('statut', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('confirmee', 'Confirmée'), ('prete', 'Prête'), ('servie', 'Servie'), ('refusee', 'Refusée'), ('annulee', 'Annulée')], default='nouvelle', max_length=10, verbose_name='statut')),
                ('mode_retrait', models.CharField(choices=[('ferme', 'Retrait à la ferme'), ('livraison', 'Livraison')], default='ferme', max_length=10, verbose_name='retrait')),
                ('adresse_livraison', models.TextField(blank=True, verbose_name='adresse de livraison')),
                ('date_souhaitee', models.DateField(blank=True, null=True, verbose_name='date souhaitée')),
                ('creneau', models.CharField(blank=True, max_length=100, verbose_name='créneau')),
                ('notes', models.TextField(blank=True, verbose_name="message de l'acheteur")),
                ('montant_ht', models.FloatField(default=0, verbose_name='total HT (€)')),
                ('montant_tva', models.FloatField(default=0, verbose_name='TVA (€)')),
                ('montant_ttc', models.FloatField(default=0, verbose_name='total TTC (€)')),
                ('confirmee_le', models.DateTimeField(blank=True, null=True)),
                ('prete_le', models.DateTimeField(blank=True, null=True)),
                ('servie_le', models.DateTimeField(blank=True, null=True)),
                ('motif_refus', models.CharField(blank=True, max_length=255, verbose_name='motif')),
                ('client_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='client.client', verbose_name='fiche client')),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='exploitations.exploitation')),
            ],
            options={
                'verbose_name': 'commande',
                'verbose_name_plural': 'commandes',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255, verbose_name='désignation')),
                ('unite_libelle', models.CharField(blank=True, max_length=50, verbose_name='unité')),
                ('quantite', models.FloatField(verbose_name='quantité')),
                ('quantite_stock', models.FloatField(default=0, verbose_name='quantité prélevée')),
                ('prix_unitaire_ttc', models.FloatField(default=0, verbose_name='prix unitaire TTC (€)')),
                ('taux_tva', models.FloatField(default=5.5, verbose_name='TVA (%)')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_vendues', to='stock.article')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='vente.commande')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes', to='vente.produit')),
            ],
            options={
                'verbose_name': 'ligne de commande',
                'verbose_name_plural': 'lignes de commande',
                'ordering': ('id',),
            },
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['exploitation', 'statut', '-created_at'], name='vente_comma_exploit_a66846_idx'),
        ),
        migrations.AddConstraint(
            model_name='commande',
            constraint=models.UniqueConstraint(fields=('exploitation', 'numero'), name='unique_commande_numero'),
        ),
        migrations.AddIndex(
            model_name='lignecommande',
            index=models.Index(fields=['article'], name='vente_ligne_article_38a516_idx'),
        ),
    ]
