# Generated by Django 5.2.15 on 2026-08-25 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0009_devis_signature_date_devis_signature_mention_and_more'),
        ('vente', '0002_commande_lignecommande_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='facture',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commande_vente', to='finances.facture', verbose_name='facture'),
        ),
    ]
