# Generated by Django 5.2.15 on 2026-09-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vente', '0003_commande_facture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.CharField(choices=[('legume', 'Légumes'), ('fruit', 'Fruits'), ('viande', 'Viande'), ('volaille', 'Volaille'), ('oeuf', 'Œufs'), ('laitier', 'Produits laitiers'), ('fromage', 'Fromages'), ('legumineuse', 'Légumineuses'), ('poisson', 'Poissons et fruits de mer'), ('cereale', 'Céréales'), ('farine', 'Farines'), ('huile', 'Huiles'), ('miel', 'Miel'), ('vin', 'Vins et spiritueux'), ('boisson', 'Jus et boissons'), ('epicerie', 'Épicerie et conserves'), ('plant', 'Plants et semences'), ('fleur', 'Fleurs'), ('fourrage', 'Fourrage et paille'), ('autre', 'Autre')], default='autre', max_length=12, verbose_name='catégorie'),
        ),
    ]
