# Generated by Django 5.2.15 on 2026-06-23 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exploitations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CultureKc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=255, verbose_name='nom')),
                ('nom_scientifique', models.CharField(blank=True, max_length=255, verbose_name='nom scientifique')),
                ('categorie', models.CharField(choices=[('cereales', 'Céréales'), ('legumes', 'Légumes'), ('fruits', 'Fruits'), ('vigne', 'Vigne'), ('oleagineux', 'Oléagineux'), ('fourrage', 'Fourrage'), ('maraichage', 'Maraîchage'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('kc_initial', models.FloatField(default=0.3)),
                ('kc_mid', models.FloatField(default=1.0)),
                ('kc_end', models.FloatField(default=0.6)),
                ('duration_initial', models.IntegerField(default=30)),
                ('duration_dev', models.IntegerField(default=40)),
                ('duration_mid', models.IntegerField(default=50)),
                ('duration_end', models.IntegerField(default=30)),
                ('source', models.CharField(default='FAO-56', max_length=100)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'culture (Kc)',
                'verbose_name_plural': 'cultures (Kc)',
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='TypeSol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=255, verbose_name='nom')),
                ('texture', models.CharField(choices=[('sableux', 'Sableux'), ('limoneux', 'Limoneux'), ('argileux', 'Argileux'), ('limon_argileux', 'Limon argileux'), ('sablo_limoneux', 'Sablo-limoneux'), ('argilo_limoneux', 'Argilo-limoneux')], default='limoneux', max_length=20)),
                ('capacite_retention_mm', models.FloatField(default=100, verbose_name='capacité de rétention (mm)')),
                ('ph_typique', models.FloatField(default=7.0, verbose_name='pH typique')),
                ('conductivite_hydraulique', models.FloatField(blank=True, null=True)),
                ('densite_apparente', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'type de sol',
                'verbose_name_plural': 'types de sol',
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='Saison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100, verbose_name='nom')),
                ('date_debut', models.DateField(verbose_name='date de début')),
                ('date_fin', models.DateField(verbose_name='date de fin')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('notes', models.TextField(blank=True)),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saisons', to='exploitations.exploitation')),
            ],
            options={
                'verbose_name': 'saison',
                'verbose_name_plural': 'saisons',
                'ordering': ('-date_debut',),
            },
        ),
    ]
