# Generated by Django 5.2.15 on 2026-06-23 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agronomie', '0001_initial'),
        ('exploitations', '0001_initial'),
        ('parcelles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fertigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('produit', models.CharField(blank=True, max_length=255)),
                ('azote_n', models.FloatField(default=0)),
                ('phosphore_p', models.FloatField(default=0)),
                ('potassium_k', models.FloatField(default=0)),
                ('volume_l', models.FloatField(default=0)),
                ('concentration', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fertigations', to='exploitations.exploitation')),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fertigations', to='parcelles.parcelle')),
            ],
            options={
                'verbose_name': 'fertigation',
                'verbose_name_plural': 'fertigations',
                'ordering': ('-date',),
            },
        ),
    ]
