# Generated by Django 5.2.15 on 2026-06-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agronomie', '0004_seed_type_sol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engrais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=255, verbose_name='nom')),
                ('type_engrais', models.CharField(choices=[('N', 'N'), ('P', 'P'), ('K', 'K'), ('NP', 'NP'), ('NK', 'NK'), ('NPK', 'NPK')], default='NPK', max_length=4, verbose_name='type')),
                ('n_pct', models.FloatField(blank=True, null=True, verbose_name='N %')),
                ('p_pct', models.FloatField(blank=True, null=True, verbose_name='P %')),
                ('k_pct', models.FloatField(blank=True, null=True, verbose_name='K %')),
                ('solubilite', models.CharField(blank=True, max_length=50, verbose_name='solubilité')),
                ('ph_effet', models.CharField(blank=True, max_length=50, verbose_name='effet pH')),
            ],
            options={
                'verbose_name': 'engrais',
                'verbose_name_plural': 'engrais',
                'ordering': ('nom',),
            },
        ),
    ]
