# Generated by Django 5.2.15 on 2026-07-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agronomie', '0006_seed_engrais'),
    ]

    operations = [
        migrations.AddField(
            model_name='culturekc',
            name='recolte_debut',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='récolte — mois de début'),
        ),
        migrations.AddField(
            model_name='culturekc',
            name='recolte_fin',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='récolte — mois de fin'),
        ),
        migrations.AddField(
            model_name='culturekc',
            name='semis_debut',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='semis — mois de début'),
        ),
        migrations.AddField(
            model_name='culturekc',
            name='semis_fin',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='semis — mois de fin'),
        ),
    ]
