# Generated by Django 5.2.15 on 2026-07-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agronomie', '0009_dedupe_cultures'),
    ]

    operations = [
        migrations.AddField(
            model_name='culturekc',
            name='arrosage',
            field=models.CharField(blank=True, choices=[('faible', 'Faible'), ('moyen', 'Moyen'), ('eleve', 'Élevé')], max_length=15, verbose_name='arrosage'),
        ),
        migrations.AddField(
            model_name='culturekc',
            name='conseil_culture',
            field=models.TextField(blank=True, verbose_name='conseil de culture'),
        ),
        migrations.AddField(
            model_name='culturekc',
            name='conseil_semis',
            field=models.TextField(blank=True, verbose_name='conseil de semis'),
        ),
        migrations.AddField(
            model_name='culturekc',
            name='contenance_sachet',
            field=models.CharField(blank=True, max_length=100, verbose_name='contenance du sachet'),
        ),
        migrations.AddField(
            model_name='culturekc',
            name='couleur',
            field=models.CharField(blank=True, max_length=100, verbose_name='couleur'),
        ),
        migrations.AddField(
            model_name='culturekc',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='culturekc',
            name='exposition',
            field=models.CharField(blank=True, choices=[('plein_soleil', 'Plein soleil'), ('mi_ombre', 'Mi-ombre'), ('ombre', 'Ombre')], max_length=15, verbose_name='exposition'),
        ),
        migrations.AddField(
            model_name='culturekc',
            name='feuillage',
            field=models.CharField(blank=True, max_length=100, verbose_name='feuillage'),
        ),
        migrations.AddField(
            model_name='culturekc',
            name='forme',
            field=models.CharField(blank=True, max_length=100, verbose_name='forme'),
        ),
        migrations.AddField(
            model_name='culturekc',
            name='mode_culture',
            field=models.CharField(blank=True, max_length=255, verbose_name='mode de culture'),
        ),
        migrations.AddField(
            model_name='culturekc',
            name='nature_sol',
            field=models.CharField(blank=True, max_length=255, verbose_name='nature du sol'),
        ),
        migrations.AddField(
            model_name='culturekc',
            name='nb_avis',
            field=models.PositiveIntegerField(default=0, verbose_name="nombre d'avis"),
        ),
        migrations.AddField(
            model_name='culturekc',
            name='note',
            field=models.FloatField(blank=True, null=True, verbose_name='note (/5)'),
        ),
        migrations.AddField(
            model_name='culturekc',
            name='origine',
            field=models.CharField(blank=True, max_length=255, verbose_name='origine'),
        ),
        migrations.AddField(
            model_name='culturekc',
            name='origine_texte',
            field=models.TextField(blank=True, verbose_name='origine (historique)'),
        ),
        migrations.AddField(
            model_name='culturekc',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cultures/', verbose_name='photo'),
        ),
        migrations.AddField(
            model_name='culturekc',
            name='poids',
            field=models.CharField(blank=True, max_length=100, verbose_name='poids'),
        ),
        migrations.AddField(
            model_name='culturekc',
            name='sol_detail',
            field=models.CharField(blank=True, max_length=255, verbose_name='sol (détail)'),
        ),
        migrations.AddField(
            model_name='culturekc',
            name='texture_fruit',
            field=models.CharField(blank=True, max_length=100, verbose_name='texture'),
        ),
        migrations.AddField(
            model_name='culturekc',
            name='type_croissance',
            field=models.CharField(blank=True, max_length=100, verbose_name='type de croissance'),
        ),
        migrations.AddField(
            model_name='culturekc',
            name='type_semis',
            field=models.CharField(blank=True, max_length=100, verbose_name='semis'),
        ),
        migrations.AddField(
            model_name='culturekc',
            name='variete',
            field=models.CharField(blank=True, max_length=255, verbose_name='variété'),
        ),
    ]
