# Generated by Django 5.2.15 on 2026-07-21 12:23

import django.db.models.deletion
from django.db import migrations, models

_VARIETY_FIELDS = [
    "variete", "photo", "description", "note", "nb_avis", "exposition", "arrosage",
    "nature_sol", "sol_detail", "mode_culture", "conseil_semis", "conseil_culture",
    "poids", "contenance_sachet", "forme", "texture_fruit", "type_croissance",
    "couleur", "feuillage", "type_semis", "origine", "origine_texte",
]


def move_varietes(apps, schema_editor):
    """Déplace les cultures qui sont en fait des variétés (fiche détaillée remplie)
    vers le modèle Variete, rattachées à leur espèce."""
    CultureKc = apps.get_model("agronomie", "CultureKc")
    Variete = apps.get_model("agronomie", "Variete")

    src = CultureKc.objects.filter(nom="Aunt Ruby's German Green").first()
    if not src:
        return
    parent = CultureKc.objects.filter(nom="Tomate").first()
    if not parent:
        parent = CultureKc.objects.create(
            nom="Tomate", nom_scientifique="Solanum lycopersicum", categorie="legumes",
            kc_initial=0.6, kc_mid=1.15, kc_end=0.8,
            semis_debut=3, semis_fin=4, recolte_debut=7, recolte_fin=10,
            source="Kokopelli / calendrier potager",
        )
    Variete.objects.create(
        culture=parent,
        nom=src.variete or src.nom,
        nom_scientifique=src.nom_scientifique,
        photo=src.photo.name if src.photo else "",
        description=src.description, note=src.note, nb_avis=src.nb_avis,
        semis_debut=src.semis_debut, semis_fin=src.semis_fin,
        recolte_debut=src.recolte_debut, recolte_fin=src.recolte_fin,
        exposition=src.exposition, arrosage=src.arrosage, nature_sol=src.nature_sol,
        sol_detail=src.sol_detail, mode_culture=src.mode_culture,
        conseil_semis=src.conseil_semis, conseil_culture=src.conseil_culture,
        poids=src.poids, contenance_sachet=src.contenance_sachet, forme=src.forme,
        texture_fruit=src.texture_fruit, type_croissance=src.type_croissance,
        couleur=src.couleur, feuillage=src.feuillage, type_semis=src.type_semis,
        origine=src.origine, origine_texte=src.origine_texte, source=src.source,
    )
    src.delete()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('agronomie', '0011_seed_variete_exemple'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=255, verbose_name='variété')),
                ('nom_scientifique', models.CharField(blank=True, max_length=255, verbose_name='nom scientifique')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cultures/', verbose_name='photo')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('note', models.FloatField(blank=True, null=True, verbose_name='note (/5)')),
                ('nb_avis', models.PositiveIntegerField(default=0, verbose_name="nombre d'avis")),
                ('semis_debut', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('semis_fin', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('recolte_debut', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('recolte_fin', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('exposition', models.CharField(blank=True, choices=[('plein_soleil', 'Plein soleil'), ('mi_ombre', 'Mi-ombre'), ('ombre', 'Ombre')], max_length=15, verbose_name='exposition')),
                ('arrosage', models.CharField(blank=True, choices=[('faible', 'Faible'), ('moyen', 'Moyen'), ('eleve', 'Élevé')], max_length=15, verbose_name='arrosage')),
                ('nature_sol', models.CharField(blank=True, max_length=255, verbose_name='nature du sol')),
                ('sol_detail', models.CharField(blank=True, max_length=255, verbose_name='sol (détail)')),
                ('mode_culture', models.CharField(blank=True, max_length=255, verbose_name='mode de culture')),
                ('conseil_semis', models.TextField(blank=True, verbose_name='conseil de semis')),
                ('conseil_culture', models.TextField(blank=True, verbose_name='conseil de culture')),
                ('poids', models.CharField(blank=True, max_length=100, verbose_name='poids')),
                ('contenance_sachet', models.CharField(blank=True, max_length=100, verbose_name='contenance du sachet')),
                ('forme', models.CharField(blank=True, max_length=100, verbose_name='forme')),
                ('texture_fruit', models.CharField(blank=True, max_length=100, verbose_name='texture')),
                ('type_croissance', models.CharField(blank=True, max_length=100, verbose_name='type de croissance')),
                ('couleur', models.CharField(blank=True, max_length=100, verbose_name='couleur')),
                ('feuillage', models.CharField(blank=True, max_length=100, verbose_name='feuillage')),
                ('type_semis', models.CharField(blank=True, max_length=100, verbose_name='semis')),
                ('origine', models.CharField(blank=True, max_length=255, verbose_name='origine')),
                ('origine_texte', models.TextField(blank=True, verbose_name='origine (historique)')),
                ('source', models.CharField(blank=True, max_length=100)),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varietes', to='agronomie.culturekc')),
            ],
            options={
                'verbose_name': 'variété',
                'verbose_name_plural': 'variétés',
                'ordering': ('nom',),
                'indexes': [models.Index(fields=['culture'], name='agronomie_v_culture_0f83b9_idx')],
            },
        ),
        migrations.RunPython(move_varietes, noop),
    ] + [
        migrations.RemoveField(model_name='culturekc', name=f) for f in _VARIETY_FIELDS
    ]
