# Generated by Django 5.2.15 on 2026-07-25 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agronomie', '0013_seed_calendrier_semis'),
        ('analyses', '0003_remove_biodiversitefiche_saison'),
        ('finances', '0002_remove_revenu_saison'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Saison',
        ),
    ]
