# Generated by Django 5.2.15 on 2026-06-23 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exploitations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('to', models.TextField(verbose_name='destinataires')),
                ('cc', models.TextField(blank=True, verbose_name='copie')),
                ('subject', models.CharField(max_length=255, verbose_name='objet')),
                ('body', models.TextField(verbose_name='message')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='pièces jointes')),
                ('status', models.CharField(choices=[('sent', 'Envoyé'), ('failed', 'Échec')], default='sent', max_length=10)),
                ('error', models.TextField(blank=True)),
                ('exploitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='exploitations.exploitation')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'e-mail',
                'verbose_name_plural': 'e-mails',
                'ordering': ('-created_at',),
            },
        ),
    ]
