# Generated by Django 5.2.15 on 2026-07-21 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Connexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée')], default='en_attente', max_length=12, verbose_name='statut')),
                ('message', models.CharField(blank=True, max_length=280, verbose_name='message de connexion')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='répondu le')),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connexions_envoyees', to=settings.AUTH_USER_MODEL, verbose_name='demandeur')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connexions_recues', to=settings.AUTH_USER_MODEL, verbose_name='destinataire')),
            ],
            options={
                'verbose_name': 'connexion',
                'verbose_name_plural': 'connexions',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['destinataire', 'statut'], name='reseaux_con_destina_786444_idx'), models.Index(fields=['demandeur', 'statut'], name='reseaux_con_demande_2b7a6d_idx')],
                'constraints': [models.UniqueConstraint(fields=('demandeur', 'destinataire'), name='uniq_connexion_paire')],
            },
        ),
    ]
