# Generated by Django 5.2.15 on 2026-07-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationrule_ville'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationrule',
            name='is_breaching',
            field=models.BooleanField(default=False, verbose_name='seuil déjà dépassé'),
        ),
        migrations.AddField(
            model_name='notificationrule',
            name='metric',
            field=models.CharField(blank=True, choices=[('temperature', 'Température'), ('ressenti', 'Température ressentie'), ('humidite', 'Humidité'), ('vent', 'Vent'), ('pluie', 'Pluie')], max_length=50, verbose_name='grandeur'),
        ),
    ]
